//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/DeepEternityDataClass.proto
namespace DeepEternity_Data
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Source_ID_Data")]
  public partial class Source_ID_Data : global::ProtoBuf.IExtensible
  {
    public Source_ID_Data() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Source_ID_State_Data")]
  public partial class Source_ID_State_Data : global::ProtoBuf.IExtensible
  {
    public Source_ID_State_Data() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _state;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Source_ID_Bool_Data")]
  public partial class Source_ID_Bool_Data : global::ProtoBuf.IExtensible
  {
    public Source_ID_Bool_Data() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private bool _state;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VECTOR3")]
  public partial class VECTOR3 : global::ProtoBuf.IExtensible
  {
    public VECTOR3() {}
    
    private float _float_X;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"float_X", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float float_X
    {
      get { return _float_X; }
      set { _float_X = value; }
    }
    private float _float_Y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"float_Y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float float_Y
    {
      get { return _float_Y; }
      set { _float_Y = value; }
    }
    private float _float_Z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"float_Z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float float_Z
    {
      get { return _float_Z; }
      set { _float_Z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DicInt")]
  public partial class DicInt : global::ProtoBuf.IExtensible
  {
    public DicInt() {}
    
    private readonly global::System.Collections.Generic.List<int> _key = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> key
    {
      get { return _key; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _value = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> value
    {
      get { return _value; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Weapon")]
  public partial class Weapon : global::ProtoBuf.IExtensible
  {
    public Weapon() {}
    
    private int _weaponType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"weaponType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int weaponType
    {
      get { return _weaponType; }
      set { _weaponType = value; }
    }
    private int _subType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"subType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int subType
    {
      get { return _subType; }
      set { _subType = value; }
    }
    private int _quantity;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"quantity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int quantity
    {
      get { return _quantity; }
      set { _quantity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WeaponList")]
  public partial class WeaponList : global::ProtoBuf.IExtensible
  {
    public WeaponList() {}
    
    private readonly global::System.Collections.Generic.List<DeepEternity_Data.Weapon> _listWeaponSpot = new global::System.Collections.Generic.List<DeepEternity_Data.Weapon>();
    [global::ProtoBuf.ProtoMember(1, Name=@"listWeaponSpot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<DeepEternity_Data.Weapon> listWeaponSpot
    {
      get { return _listWeaponSpot; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DE_Monster_Info")]
  public partial class DE_Monster_Info : global::ProtoBuf.IExtensible
  {
    public DE_Monster_Info() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _spawnTimes;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"spawnTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int spawnTimes
    {
      get { return _spawnTimes; }
      set { _spawnTimes = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _attackSpeed;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"attackSpeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attackSpeed
    {
      get { return _attackSpeed; }
      set { _attackSpeed = value; }
    }
    private float _attackInterval;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"attackInterval", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float attackInterval
    {
      get { return _attackInterval; }
      set { _attackInterval = value; }
    }
    private int _damage;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private float _moveSpeed;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"moveSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float moveSpeed
    {
      get { return _moveSpeed; }
      set { _moveSpeed = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private int _dispearedTime;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"dispearedTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dispearedTime
    {
      get { return _dispearedTime; }
      set { _dispearedTime = value; }
    }
    private float _attackDistance;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"attackDistance", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float attackDistance
    {
      get { return _attackDistance; }
      set { _attackDistance = value; }
    }
    private int _itemType;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"itemType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemType
    {
      get { return _itemType; }
      set { _itemType = value; }
    }
    private int _subItemType;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"subItemType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int subItemType
    {
      get { return _subItemType; }
      set { _subItemType = value; }
    }
    private int _quantity;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"quantity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int quantity
    {
      get { return _quantity; }
      set { _quantity = value; }
    }
    private DeepEternity_Data.VECTOR3 _startPos;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"startPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public DeepEternity_Data.VECTOR3 startPos
    {
      get { return _startPos; }
      set { _startPos = value; }
    }
    private int _playerId;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _items;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string items
    {
      get { return _items; }
      set { _items = value; }
    }
    private DeepEternity_Data.VECTOR3 _patrolpos1;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"patrolpos1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public DeepEternity_Data.VECTOR3 patrolpos1
    {
      get { return _patrolpos1; }
      set { _patrolpos1 = value; }
    }
    private DeepEternity_Data.VECTOR3 _patrolpos2;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"patrolpos2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public DeepEternity_Data.VECTOR3 patrolpos2
    {
      get { return _patrolpos2; }
      set { _patrolpos2 = value; }
    }
    private DeepEternity_Data.VECTOR3 _patrolpos3;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"patrolpos3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public DeepEternity_Data.VECTOR3 patrolpos3
    {
      get { return _patrolpos3; }
      set { _patrolpos3 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpawnDE_Monster_MSG")]
  public partial class SpawnDE_Monster_MSG : global::ProtoBuf.IExtensible
  {
    public SpawnDE_Monster_MSG() {}
    
    private DeepEternity_Data.DE_Monster_Info _monsterInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"monsterInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public DeepEternity_Data.DE_Monster_Info monsterInfo
    {
      get { return _monsterInfo; }
      set { _monsterInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Damage_Info")]
  public partial class Damage_Info : global::ProtoBuf.IExtensible
  {
    public Damage_Info() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _damage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private int _gunType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"gunType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gunType
    {
      get { return _gunType; }
      set { _gunType = value; }
    }
    private int _playerId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipWeapon_Info")]
  public partial class EquipWeapon_Info : global::ProtoBuf.IExtensible
  {
    public EquipWeapon_Info() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _spot;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"spot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int spot
    {
      get { return _spot; }
      set { _spot = value; }
    }
    private int _weaponType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"weaponType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int weaponType
    {
      get { return _weaponType; }
      set { _weaponType = value; }
    }
    private int _subType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"subType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int subType
    {
      get { return _subType; }
      set { _subType = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DE_MonsterDie_Info")]
  public partial class DE_MonsterDie_Info : global::ProtoBuf.IExtensible
  {
    public DE_MonsterDie_Info() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _playerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _gunType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"gunType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gunType
    {
      get { return _gunType; }
      set { _gunType = value; }
    }
    private string _items;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string items
    {
      get { return _items; }
      set { _items = value; }
    }
    private int _quantity;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"quantity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int quantity
    {
      get { return _quantity; }
      set { _quantity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerDamage_Info")]
  public partial class PlayerDamage_Info : global::ProtoBuf.IExtensible
  {
    public PlayerDamage_Info() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _damage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private int _monsterId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"monsterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int monsterId
    {
      get { return _monsterId; }
      set { _monsterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpawnDE_MonsterNum")]
  public partial class SpawnDE_MonsterNum : global::ProtoBuf.IExtensible
  {
    public SpawnDE_MonsterNum() {}
    
    private int _waves;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"waves", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int waves
    {
      get { return _waves; }
      set { _waves = value; }
    }
    private int _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DE_SpawnInfo")]
  public partial class DE_SpawnInfo : global::ProtoBuf.IExtensible
  {
    public DE_SpawnInfo() {}
    
    private int _roomid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomid
    {
      get { return _roomid; }
      set { _roomid = value; }
    }
    private int _cellOutside;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cellOutside", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cellOutside
    {
      get { return _cellOutside; }
      set { _cellOutside = value; }
    }
    private int _cellInside;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cellInside", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cellInside
    {
      get { return _cellInside; }
      set { _cellInside = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CellEnemyInfo")]
  public partial class CellEnemyInfo : global::ProtoBuf.IExtensible
  {
    public CellEnemyInfo() {}
    
    private int _cellId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cellId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cellId
    {
      get { return _cellId; }
      set { _cellId = value; }
    }
    private int _refreshCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"refreshCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int refreshCount
    {
      get { return _refreshCount; }
      set { _refreshCount = value; }
    }
    private int _leftEnemies;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"leftEnemies", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int leftEnemies
    {
      get { return _leftEnemies; }
      set { _leftEnemies = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CellEnemyList")]
  public partial class CellEnemyList : global::ProtoBuf.IExtensible
  {
    public CellEnemyList() {}
    
    private readonly global::System.Collections.Generic.List<DeepEternity_Data.CellEnemyInfo> _listCellEnemyInfo = new global::System.Collections.Generic.List<DeepEternity_Data.CellEnemyInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"listCellEnemyInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<DeepEternity_Data.CellEnemyInfo> listCellEnemyInfo
    {
      get { return _listCellEnemyInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}