//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/msg_5_activity.proto
namespace ACTIVITY_MSG
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_STREET_DANCE_MSG")]
  public partial class STC_STREET_DANCE_MSG : global::ProtoBuf.IExtensible
  {
    public STC_STREET_DANCE_MSG() {}
    
    private uint _DANCE_INDEX;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"DANCE_INDEX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint DANCE_INDEX
    {
      get { return _DANCE_INDEX; }
      set { _DANCE_INDEX = value; }
    }
    private uint _DANCE_TIME;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"DANCE_TIME", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint DANCE_TIME
    {
      get { return _DANCE_TIME; }
      set { _DANCE_TIME = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_STREET_CMD_MSG")]
  public partial class CTS_STREET_CMD_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_STREET_CMD_MSG() {}
    
    private string _CMD_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"CMD_ID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string CMD_ID
    {
      get { return _CMD_ID; }
      set { _CMD_ID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_STREET_CMD_MSG")]
  public partial class STC_STREET_CMD_MSG : global::ProtoBuf.IExtensible
  {
    public STC_STREET_CMD_MSG() {}
    
    private string _CMD_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"CMD_ID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string CMD_ID
    {
      get { return _CMD_ID; }
      set { _CMD_ID = value; }
    }
    private ACTIVITY_MSG.ACTION_RESULT _RESULT;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RESULT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ACTIVITY_MSG.ACTION_RESULT RESULT
    {
      get { return _RESULT; }
      set { _RESULT = value; }
    }

    private string _INFO = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string INFO
    {
      get { return _INFO; }
      set { _INFO = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CMD_TYPE")]
    public enum CMD_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_TYPE_ACTIVITY", Value=5)]
      MSG_TYPE_ACTIVITY = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ACTION_RESULT")]
    public enum ACTION_RESULT
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAILED", Value=2)]
      FAILED = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CMD_ID")]
    public enum CMD_ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_STREET_DANCE", Value=1)]
      STC_STREET_DANCE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_STREET_DANCE", Value=2)]
      CTS_STREET_DANCE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_STREET_CMD", Value=3)]
      CTS_STREET_CMD = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_STREET_CMD", Value=4)]
      STC_STREET_CMD = 4
    }
  
}