//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/msg_1_account.proto
namespace ACCOUNT_MSG
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_PASSWORD_LOGIN_MSG")]
  public partial class CTS_PASSWORD_LOGIN_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_PASSWORD_LOGIN_MSG() {}
    
    private string _username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_LOGIN_MSG")]
  public partial class STC_LOGIN_MSG : global::ProtoBuf.IExtensible
  {
    public STC_LOGIN_MSG() {}
    
    private ACCOUNT_MSG.LOGIN_STATE _state;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ACCOUNT_MSG.LOGIN_STATE state
    {
      get { return _state; }
      set { _state = value; }
    }

    private string _info = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string info
    {
      get { return _info; }
      set { _info = value; }
    }

    private string _token = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }

    private byte[] _iv = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"iv", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] iv
    {
      get { return _iv; }
      set { _iv = value; }
    }

    private byte[] _key = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] key
    {
      get { return _key; }
      set { _key = value; }
    }

    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }

    private string _address = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string address
    {
      get { return _address; }
      set { _address = value; }
    }

    private uint _port = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_REGIST_MSG")]
  public partial class CTS_REGIST_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_REGIST_MSG() {}
    
    private string _userName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _identityCode;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"identityCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string identityCode
    {
      get { return _identityCode; }
      set { _identityCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_REGIST_MSG")]
  public partial class STC_REGIST_MSG : global::ProtoBuf.IExtensible
  {
    public STC_REGIST_MSG() {}
    
    private uint _state;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }

    private string _info = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_REGIST_IDENTITY_MSG")]
  public partial class STC_REGIST_IDENTITY_MSG : global::ProtoBuf.IExtensible
  {
    public STC_REGIST_IDENTITY_MSG() {}
    
    private string _identityCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"identityCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string identityCode
    {
      get { return _identityCode; }
      set { _identityCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_REGIST_IDENTITY_MSG")]
  public partial class CTS_REGIST_IDENTITY_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_REGIST_IDENTITY_MSG() {}
    
    private string _telephone;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"telephone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string telephone
    {
      get { return _telephone; }
      set { _telephone = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_RESET_PASSWORD_MSG")]
  public partial class CTS_RESET_PASSWORD_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_RESET_PASSWORD_MSG() {}
    
    private string _userName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _identityCode;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"identityCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string identityCode
    {
      get { return _identityCode; }
      set { _identityCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CMD_TYPE")]
    public enum CMD_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_TYPE_ACCOUNT", Value=1)]
      MSG_TYPE_ACCOUNT = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CMD_ID")]
    public enum CMD_ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_PASSWORD_LOGIN", Value=1)]
      CTS_PASSWORD_LOGIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_LOGIN", Value=2)]
      STC_LOGIN = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_GUEST_LOGIN", Value=3)]
      CTS_GUEST_LOGIN = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_REGIST", Value=4)]
      CTS_REGIST = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_REGIST", Value=5)]
      STC_REGIST = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_REGIST_IDENTITY", Value=6)]
      CTS_REGIST_IDENTITY = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_REGIST_IDENTITY", Value=7)]
      STC_REGIST_IDENTITY = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_RESET_PASSWORD", Value=8)]
      CTS_RESET_PASSWORD = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LOGIN_STATE")]
    public enum LOGIN_STATE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PASSWORD_LOGIN_SUCCESS", Value=1)]
      PASSWORD_LOGIN_SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GUEST_LOGIN_SUCCESS", Value=2)]
      GUEST_LOGIN_SUCCESS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESET_LOGIN_SUCCESS", Value=3)]
      RESET_LOGIN_SUCCESS = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAILURE", Value=4)]
      FAILURE = 4
    }
  
}