//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/msg_13_collocation.proto
namespace COLLOCATION_MSG
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_TRIAL_MSG")]
  public partial class CTS_TRIAL_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_TRIAL_MSG() {}
    
    private uint _EVENT_TYPE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"EVENT_TYPE", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint EVENT_TYPE
    {
      get { return _EVENT_TYPE; }
      set { _EVENT_TYPE = value; }
    }
    private uint _EVENT_ID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"EVENT_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint EVENT_ID
    {
      get { return _EVENT_ID; }
      set { _EVENT_ID = value; }
    }

    private byte[] _EVENT_DATA = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"EVENT_DATA", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] EVENT_DATA
    {
      get { return _EVENT_DATA; }
      set { _EVENT_DATA = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_TRIAL_MSG")]
  public partial class STC_TRIAL_MSG : global::ProtoBuf.IExtensible
  {
    public STC_TRIAL_MSG() {}
    
    private uint _EVENT_TYPE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"EVENT_TYPE", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint EVENT_TYPE
    {
      get { return _EVENT_TYPE; }
      set { _EVENT_TYPE = value; }
    }
    private uint _EVENT_ID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"EVENT_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint EVENT_ID
    {
      get { return _EVENT_ID; }
      set { _EVENT_ID = value; }
    }

    private byte[] _EVENT_DATA = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"EVENT_DATA", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] EVENT_DATA
    {
      get { return _EVENT_DATA; }
      set { _EVENT_DATA = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_SYNC_MSG")]
  public partial class CTS_SYNC_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_SYNC_MSG() {}
    
    private uint _EVENT_TYPE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"EVENT_TYPE", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint EVENT_TYPE
    {
      get { return _EVENT_TYPE; }
      set { _EVENT_TYPE = value; }
    }

    private byte[] _EVENT_DATA = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"EVENT_DATA", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] EVENT_DATA
    {
      get { return _EVENT_DATA; }
      set { _EVENT_DATA = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_SYNC_MSG")]
  public partial class STC_SYNC_MSG : global::ProtoBuf.IExtensible
  {
    public STC_SYNC_MSG() {}
    
    private uint _EVENT_TYPE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"EVENT_TYPE", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint EVENT_TYPE
    {
      get { return _EVENT_TYPE; }
      set { _EVENT_TYPE = value; }
    }

    private byte[] _EVENT_DATA = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"EVENT_DATA", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] EVENT_DATA
    {
      get { return _EVENT_DATA; }
      set { _EVENT_DATA = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CMD_TYPE")]
    public enum CMD_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_TYPE_COLLOCATION", Value=13)]
      MSG_TYPE_COLLOCATION = 13
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CMD_ID")]
    public enum CMD_ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_TRIAL", Value=1)]
      CTS_TRIAL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_TRIAL", Value=2)]
      STC_TRIAL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_SYNC", Value=3)]
      CTS_SYNC = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_SYNC", Value=4)]
      STC_SYNC = 4
    }
  
}