//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/msg_7_melody.proto
namespace MELODY_MSG
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"COLLECTION_INFO")]
  public partial class COLLECTION_INFO : global::ProtoBuf.IExtensible
  {
    public COLLECTION_INFO() {}
    
    private uint _AUDIO_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"AUDIO_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AUDIO_ID
    {
      get { return _AUDIO_ID; }
      set { _AUDIO_ID = value; }
    }
    private string _AUDIO_KEY;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"AUDIO_KEY", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AUDIO_KEY
    {
      get { return _AUDIO_KEY; }
      set { _AUDIO_KEY = value; }
    }
    private string _AUDIO_NAME;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"AUDIO_NAME", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AUDIO_NAME
    {
      get { return _AUDIO_NAME; }
      set { _AUDIO_NAME = value; }
    }
    private uint _AUDIO_DURATION;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"AUDIO_DURATION", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AUDIO_DURATION
    {
      get { return _AUDIO_DURATION; }
      set { _AUDIO_DURATION = value; }
    }
    private uint _CASTER_ID;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"CASTER_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint CASTER_ID
    {
      get { return _CASTER_ID; }
      set { _CASTER_ID = value; }
    }
    private string _CASTER_NAME;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"CASTER_NAME", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string CASTER_NAME
    {
      get { return _CASTER_NAME; }
      set { _CASTER_NAME = value; }
    }
    private string _CASTER_PICTURE_KEY;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"CASTER_PICTURE_KEY", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string CASTER_PICTURE_KEY
    {
      get { return _CASTER_PICTURE_KEY; }
      set { _CASTER_PICTURE_KEY = value; }
    }
    private bool _COLLECT;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"COLLECT", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool COLLECT
    {
      get { return _COLLECT; }
      set { _COLLECT = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AUDIO_INFO")]
  public partial class AUDIO_INFO : global::ProtoBuf.IExtensible
  {
    public AUDIO_INFO() {}
    
    private uint _AUDIO_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"AUDIO_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AUDIO_ID
    {
      get { return _AUDIO_ID; }
      set { _AUDIO_ID = value; }
    }
    private string _AUDIO_KEY;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"AUDIO_KEY", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AUDIO_KEY
    {
      get { return _AUDIO_KEY; }
      set { _AUDIO_KEY = value; }
    }
    private string _AUDIO_NAME;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"AUDIO_NAME", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AUDIO_NAME
    {
      get { return _AUDIO_NAME; }
      set { _AUDIO_NAME = value; }
    }
    private ulong _UPLOAD_TIME;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"UPLOAD_TIME", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UPLOAD_TIME
    {
      get { return _UPLOAD_TIME; }
      set { _UPLOAD_TIME = value; }
    }
    private bool _COLLECTED;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"COLLECTED", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool COLLECTED
    {
      get { return _COLLECTED; }
      set { _COLLECTED = value; }
    }
    private bool _LIKED;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"LIKED", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool LIKED
    {
      get { return _LIKED; }
      set { _LIKED = value; }
    }
    private int _PLAY_COUNTS;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"PLAY_COUNTS", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PLAY_COUNTS
    {
      get { return _PLAY_COUNTS; }
      set { _PLAY_COUNTS = value; }
    }
    private int _LIKES_COUNT;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"LIKES_COUNT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int LIKES_COUNT
    {
      get { return _LIKES_COUNT; }
      set { _LIKES_COUNT = value; }
    }
    private int _DURATION;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"DURATION", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int DURATION
    {
      get { return _DURATION; }
      set { _DURATION = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CASTER_INFO")]
  public partial class CASTER_INFO : global::ProtoBuf.IExtensible
  {
    public CASTER_INFO() {}
    
    private string _CASTER_NAME;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"CASTER_NAME", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string CASTER_NAME
    {
      get { return _CASTER_NAME; }
      set { _CASTER_NAME = value; }
    }
    private uint _CASTER_ID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"CASTER_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint CASTER_ID
    {
      get { return _CASTER_ID; }
      set { _CASTER_ID = value; }
    }
    private uint _HEAT;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"HEAT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint HEAT
    {
      get { return _HEAT; }
      set { _HEAT = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_COLLECTION_MSG")]
  public partial class STC_COLLECTION_MSG : global::ProtoBuf.IExtensible
  {
    public STC_COLLECTION_MSG() {}
    
    private readonly global::System.Collections.Generic.List<MELODY_MSG.COLLECTION_INFO> _LIST_COLLECTION_INFO = new global::System.Collections.Generic.List<MELODY_MSG.COLLECTION_INFO>();
    [global::ProtoBuf.ProtoMember(1, Name=@"LIST_COLLECTION_INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MELODY_MSG.COLLECTION_INFO> LIST_COLLECTION_INFO
    {
      get { return _LIST_COLLECTION_INFO; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_COLLECT_MSG")]
  public partial class CTS_COLLECT_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_COLLECT_MSG() {}
    
    private uint _AUDIO_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"AUDIO_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AUDIO_ID
    {
      get { return _AUDIO_ID; }
      set { _AUDIO_ID = value; }
    }
    private bool _COLLECTED;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"COLLECTED", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool COLLECTED
    {
      get { return _COLLECTED; }
      set { _COLLECTED = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_COLLECT_MSG")]
  public partial class STC_COLLECT_MSG : global::ProtoBuf.IExtensible
  {
    public STC_COLLECT_MSG() {}
    
    private uint _RESULT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RESULT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RESULT
    {
      get { return _RESULT; }
      set { _RESULT = value; }
    }

    private string _RESULT_INFO = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"RESULT_INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string RESULT_INFO
    {
      get { return _RESULT_INFO; }
      set { _RESULT_INFO = value; }
    }
    private uint _AUDIO_ID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"AUDIO_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AUDIO_ID
    {
      get { return _AUDIO_ID; }
      set { _AUDIO_ID = value; }
    }
    private bool _COLLECTED;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"COLLECTED", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool COLLECTED
    {
      get { return _COLLECTED; }
      set { _COLLECTED = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_LIKE_MSG")]
  public partial class CTS_LIKE_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_LIKE_MSG() {}
    
    private uint _AUDIO_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"AUDIO_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AUDIO_ID
    {
      get { return _AUDIO_ID; }
      set { _AUDIO_ID = value; }
    }
    private bool _LIKED;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"LIKED", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool LIKED
    {
      get { return _LIKED; }
      set { _LIKED = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_LIKE_MSG")]
  public partial class STC_LIKE_MSG : global::ProtoBuf.IExtensible
  {
    public STC_LIKE_MSG() {}
    
    private uint _RESULT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RESULT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RESULT
    {
      get { return _RESULT; }
      set { _RESULT = value; }
    }

    private string _RESULT_INFO = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"RESULT_INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string RESULT_INFO
    {
      get { return _RESULT_INFO; }
      set { _RESULT_INFO = value; }
    }
    private uint _AUDIO_ID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"AUDIO_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AUDIO_ID
    {
      get { return _AUDIO_ID; }
      set { _AUDIO_ID = value; }
    }
    private bool _LIKED;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"LIKED", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool LIKED
    {
      get { return _LIKED; }
      set { _LIKED = value; }
    }
    private uint _LIKES_COUNT;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"LIKES_COUNT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LIKES_COUNT
    {
      get { return _LIKES_COUNT; }
      set { _LIKES_COUNT = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_CASTERS_MSG")]
  public partial class CTS_CASTERS_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_CASTERS_MSG() {}
    
    private uint _CASTER_COUNT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"CASTER_COUNT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint CASTER_COUNT
    {
      get { return _CASTER_COUNT; }
      set { _CASTER_COUNT = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_CASTERS_MSG")]
  public partial class STC_CASTERS_MSG : global::ProtoBuf.IExtensible
  {
    public STC_CASTERS_MSG() {}
    
    private readonly global::System.Collections.Generic.List<MELODY_MSG.CASTER_INFO> _LIST_CASTER = new global::System.Collections.Generic.List<MELODY_MSG.CASTER_INFO>();
    [global::ProtoBuf.ProtoMember(1, Name=@"LIST_CASTER", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MELODY_MSG.CASTER_INFO> LIST_CASTER
    {
      get { return _LIST_CASTER; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_PLAYLIST_MSG")]
  public partial class STC_PLAYLIST_MSG : global::ProtoBuf.IExtensible
  {
    public STC_PLAYLIST_MSG() {}
    
    private string _CASTER_PICTURE_KEY;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"CASTER_PICTURE_KEY", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string CASTER_PICTURE_KEY
    {
      get { return _CASTER_PICTURE_KEY; }
      set { _CASTER_PICTURE_KEY = value; }
    }
    private readonly global::System.Collections.Generic.List<MELODY_MSG.AUDIO_INFO> _LIST_AUDIO = new global::System.Collections.Generic.List<MELODY_MSG.AUDIO_INFO>();
    [global::ProtoBuf.ProtoMember(2, Name=@"LIST_AUDIO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MELODY_MSG.AUDIO_INFO> LIST_AUDIO
    {
      get { return _LIST_AUDIO; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_PLAYLIST_MSG")]
  public partial class CTS_PLAYLIST_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_PLAYLIST_MSG() {}
    
    private uint _CASTER_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"CASTER_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint CASTER_ID
    {
      get { return _CASTER_ID; }
      set { _CASTER_ID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_ENTER_MSG")]
  public partial class STC_ENTER_MSG : global::ProtoBuf.IExtensible
  {
    public STC_ENTER_MSG() {}
    
    private uint _RESULT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RESULT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RESULT
    {
      get { return _RESULT; }
      set { _RESULT = value; }
    }

    private string _RESULT_INFO = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"RESULT_INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string RESULT_INFO
    {
      get { return _RESULT_INFO; }
      set { _RESULT_INFO = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_PLAY_MSG")]
  public partial class CTS_PLAY_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_PLAY_MSG() {}
    
    private uint _AUDIO_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"AUDIO_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AUDIO_ID
    {
      get { return _AUDIO_ID; }
      set { _AUDIO_ID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_PLAY_MSG")]
  public partial class STC_PLAY_MSG : global::ProtoBuf.IExtensible
  {
    public STC_PLAY_MSG() {}
    
    private uint _RESULT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RESULT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RESULT
    {
      get { return _RESULT; }
      set { _RESULT = value; }
    }

    private string _RESULT_INFO = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"RESULT_INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string RESULT_INFO
    {
      get { return _RESULT_INFO; }
      set { _RESULT_INFO = value; }
    }
    private uint _AUDIO_ID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"AUDIO_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AUDIO_ID
    {
      get { return _AUDIO_ID; }
      set { _AUDIO_ID = value; }
    }
    private uint _PLAY_COUNT;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"PLAY_COUNT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PLAY_COUNT
    {
      get { return _PLAY_COUNT; }
      set { _PLAY_COUNT = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CMD_TYPE")]
    public enum CMD_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_TYPE_MELODY", Value=7)]
      MSG_TYPE_MELODY = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CMD_ID")]
    public enum CMD_ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_COLLECTION", Value=1)]
      STC_COLLECTION = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_COLLECTION", Value=2)]
      CTS_COLLECTION = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_COLLECT", Value=3)]
      STC_COLLECT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_COLLECT", Value=4)]
      CTS_COLLECT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_LIKE", Value=5)]
      STC_LIKE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_LIKE", Value=6)]
      CTS_LIKE = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_CASTERS", Value=7)]
      STC_CASTERS = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_CASTERS", Value=8)]
      CTS_CASTERS = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_PLAYLIST", Value=9)]
      STC_PLAYLIST = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_PLAYLIST", Value=10)]
      CTS_PLAYLIST = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_ENTER", Value=11)]
      STC_ENTER = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_ENTER", Value=12)]
      CTS_ENTER = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_PLAY", Value=13)]
      STC_PLAY = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_PLAY", Value=14)]
      CTS_PLAY = 14
    }
  
}