//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/msg_11_storage.proto
namespace STORAGE_MSG
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_SET_STORAGE_MSG")]
  public partial class CTS_SET_STORAGE_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_SET_STORAGE_MSG() {}
    
    private string _KEY;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"KEY", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string KEY
    {
      get { return _KEY; }
      set { _KEY = value; }
    }

    private byte[] _DATA = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"DATA", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] DATA
    {
      get { return _DATA; }
      set { _DATA = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_GET_STORAGE_MSG")]
  public partial class CTS_GET_STORAGE_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_GET_STORAGE_MSG() {}
    
    private string _KEY;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"KEY", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string KEY
    {
      get { return _KEY; }
      set { _KEY = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_GET_STORAGE_MSG")]
  public partial class STC_GET_STORAGE_MSG : global::ProtoBuf.IExtensible
  {
    public STC_GET_STORAGE_MSG() {}
    
    private STORAGE_MSG.ACTION_RESULT _RESULT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RESULT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public STORAGE_MSG.ACTION_RESULT RESULT
    {
      get { return _RESULT; }
      set { _RESULT = value; }
    }

    private string _INFO = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string INFO
    {
      get { return _INFO; }
      set { _INFO = value; }
    }

    private string _KEY = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"KEY", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string KEY
    {
      get { return _KEY; }
      set { _KEY = value; }
    }

    private byte[] _DATA = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"DATA", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] DATA
    {
      get { return _DATA; }
      set { _DATA = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_GET_GLOBAL_MSG")]
  public partial class CTS_GET_GLOBAL_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_GET_GLOBAL_MSG() {}
    
    private uint _PLAYER_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PLAYER_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PLAYER_ID
    {
      get { return _PLAYER_ID; }
      set { _PLAYER_ID = value; }
    }
    private string _KEY;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"KEY", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string KEY
    {
      get { return _KEY; }
      set { _KEY = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_GET_GLOBAL_MSG")]
  public partial class STC_GET_GLOBAL_MSG : global::ProtoBuf.IExtensible
  {
    public STC_GET_GLOBAL_MSG() {}
    
    private STORAGE_MSG.ACTION_RESULT _RESULT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RESULT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public STORAGE_MSG.ACTION_RESULT RESULT
    {
      get { return _RESULT; }
      set { _RESULT = value; }
    }

    private string _INFO = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string INFO
    {
      get { return _INFO; }
      set { _INFO = value; }
    }

    private string _KEY = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"KEY", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string KEY
    {
      get { return _KEY; }
      set { _KEY = value; }
    }

    private byte[] _DATA = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"DATA", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] DATA
    {
      get { return _DATA; }
      set { _DATA = value; }
    }

    private uint _PLAYER_ID = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"PLAYER_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint PLAYER_ID
    {
      get { return _PLAYER_ID; }
      set { _PLAYER_ID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerCoinData")]
  public partial class PlayerCoinData : global::ProtoBuf.IExtensible
  {
    public PlayerCoinData() {}
    
    private uint _goldCoin;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"goldCoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint goldCoin
    {
      get { return _goldCoin; }
      set { _goldCoin = value; }
    }
    private uint _creditCoin;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"creditCoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint creditCoin
    {
      get { return _creditCoin; }
      set { _creditCoin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CMD_TYPE")]
    public enum CMD_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_TYPE_STORAGE", Value=11)]
      MSG_TYPE_STORAGE = 11
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CMD_ID")]
    public enum CMD_ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_SET_STORAGE", Value=1)]
      CTS_SET_STORAGE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_GET_STORAGE", Value=2)]
      CTS_GET_STORAGE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_GET_STORAGE", Value=3)]
      STC_GET_STORAGE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_GET_GLOBAL", Value=4)]
      CTS_GET_GLOBAL = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_GET_GLOBAL", Value=5)]
      STC_GET_GLOBAL = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ACTION_RESULT")]
    public enum ACTION_RESULT
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAILED", Value=2)]
      FAILED = 2
    }
  
}