//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/msg_public_subscribe.proto
// Note: requires additional types generated from: HardCordGirlDataClass.proto
namespace msg_public_subscribe
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"subscribe_Property_pos_msg")]
  public partial class subscribe_Property_pos_msg : global::ProtoBuf.IExtensible
  {
    public subscribe_Property_pos_msg() {}
    
    private HardCordGirl_Data.VECTOR3 _BodyPos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"BodyPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public HardCordGirl_Data.VECTOR3 BodyPos
    {
      get { return _BodyPos; }
      set { _BodyPos = value; }
    }
    private HardCordGirl_Data.VECTOR3 _BodyRot;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"BodyRot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public HardCordGirl_Data.VECTOR3 BodyRot
    {
      get { return _BodyRot; }
      set { _BodyRot = value; }
    }
    private HardCordGirl_Data.VECTOR3 _HandPos_Right;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"HandPos_Right", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public HardCordGirl_Data.VECTOR3 HandPos_Right
    {
      get { return _HandPos_Right; }
      set { _HandPos_Right = value; }
    }
    private HardCordGirl_Data.VECTOR3 _HandRot_Right;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"HandRot_Right", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public HardCordGirl_Data.VECTOR3 HandRot_Right
    {
      get { return _HandRot_Right; }
      set { _HandRot_Right = value; }
    }
    private HardCordGirl_Data.VECTOR3 _HandPos_Left;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"HandPos_Left", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public HardCordGirl_Data.VECTOR3 HandPos_Left
    {
      get { return _HandPos_Left; }
      set { _HandPos_Left = value; }
    }
    private HardCordGirl_Data.VECTOR3 _HandRot_Left;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"HandRot_Left", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public HardCordGirl_Data.VECTOR3 HandRot_Left
    {
      get { return _HandRot_Left; }
      set { _HandRot_Left = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"subscribe_Property_msg")]
  public partial class subscribe_Property_msg : global::ProtoBuf.IExtensible
  {
    public subscribe_Property_msg() {}
    

    private int _UID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"UID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int UID
    {
      get { return _UID; }
      set { _UID = value; }
    }

    private string _Name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }

    private int _Characteristic = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Characteristic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Characteristic
    {
      get { return _Characteristic; }
      set { _Characteristic = value; }
    }

    private int _Level = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }

    private int _Permission = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Permission", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Permission
    {
      get { return _Permission; }
      set { _Permission = value; }
    }

    private int _Title = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Title", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Title
    {
      get { return _Title; }
      set { _Title = value; }
    }

    private int _RoomIndex = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"RoomIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RoomIndex
    {
      get { return _RoomIndex; }
      set { _RoomIndex = value; }
    }

    private int _State = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"State", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int State
    {
      get { return _State; }
      set { _State = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"subscribe_ID_msg")]
  public partial class subscribe_ID_msg : global::ProtoBuf.IExtensible
  {
    public subscribe_ID_msg() {}
    

    private int _UID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"UID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int UID
    {
      get { return _UID; }
      set { _UID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"subscribe_KtvScore_msg")]
  public partial class subscribe_KtvScore_msg : global::ProtoBuf.IExtensible
  {
    public subscribe_KtvScore_msg() {}
    

    private string _SongName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SongName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SongName
    {
      get { return _SongName; }
      set { _SongName = value; }
    }

    private string _PlayerName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"PlayerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PlayerName
    {
      get { return _PlayerName; }
      set { _PlayerName = value; }
    }

    private int _Score = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Score
    {
      get { return _Score; }
      set { _Score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"subscribe_KtvVote_msg")]
  public partial class subscribe_KtvVote_msg : global::ProtoBuf.IExtensible
  {
    public subscribe_KtvVote_msg() {}
    

    private string _SongName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SongName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SongName
    {
      get { return _SongName; }
      set { _SongName = value; }
    }

    private int _SongPlayerId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SongPlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SongPlayerId
    {
      get { return _SongPlayerId; }
      set { _SongPlayerId = value; }
    }

    private string _PlayerName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"PlayerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PlayerName
    {
      get { return _PlayerName; }
      set { _PlayerName = value; }
    }

    private int _SongIndex = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"SongIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SongIndex
    {
      get { return _SongIndex; }
      set { _SongIndex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VoteInfo_msg")]
  public partial class VoteInfo_msg : global::ProtoBuf.IExtensible
  {
    public VoteInfo_msg() {}
    

    private string _SongName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SongName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SongName
    {
      get { return _SongName; }
      set { _SongName = value; }
    }

    private string _PlayerName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"PlayerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PlayerName
    {
      get { return _PlayerName; }
      set { _PlayerName = value; }
    }

    private int _PlayerId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"PlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int PlayerId
    {
      get { return _PlayerId; }
      set { _PlayerId = value; }
    }

    private int _Num = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Num
    {
      get { return _Num; }
      set { _Num = value; }
    }

    private string _Head = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Head", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Head
    {
      get { return _Head; }
      set { _Head = value; }
    }

    private int _Characteristic = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Characteristic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Characteristic
    {
      get { return _Characteristic; }
      set { _Characteristic = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"subscribe_VoteInfoList_msg")]
  public partial class subscribe_VoteInfoList_msg : global::ProtoBuf.IExtensible
  {
    public subscribe_VoteInfoList_msg() {}
    
    private readonly global::System.Collections.Generic.List<msg_public_subscribe.VoteInfo_msg> _VoteInfos = new global::System.Collections.Generic.List<msg_public_subscribe.VoteInfo_msg>();
    [global::ProtoBuf.ProtoMember(1, Name=@"VoteInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<msg_public_subscribe.VoteInfo_msg> VoteInfos
    {
      get { return _VoteInfos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AnswerInfo_msg")]
  public partial class AnswerInfo_msg : global::ProtoBuf.IExtensible
  {
    public AnswerInfo_msg() {}
    

    private string _PlayerName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"PlayerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PlayerName
    {
      get { return _PlayerName; }
      set { _PlayerName = value; }
    }

    private int _PlayerId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"PlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int PlayerId
    {
      get { return _PlayerId; }
      set { _PlayerId = value; }
    }

    private string _Head = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Head", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Head
    {
      get { return _Head; }
      set { _Head = value; }
    }

    private int _Characteristic = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Characteristic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Characteristic
    {
      get { return _Characteristic; }
      set { _Characteristic = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"subscribe_AnswerInfoList_msg")]
  public partial class subscribe_AnswerInfoList_msg : global::ProtoBuf.IExtensible
  {
    public subscribe_AnswerInfoList_msg() {}
    
    private readonly global::System.Collections.Generic.List<msg_public_subscribe.AnswerInfo_msg> _AnswerInfos = new global::System.Collections.Generic.List<msg_public_subscribe.AnswerInfo_msg>();
    [global::ProtoBuf.ProtoMember(1, Name=@"AnswerInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<msg_public_subscribe.AnswerInfo_msg> AnswerInfos
    {
      get { return _AnswerInfos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"subscribe_Volume_msg")]
  public partial class subscribe_Volume_msg : global::ProtoBuf.IExtensible
  {
    public subscribe_Volume_msg() {}
    

    private float _MicVolume = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"MicVolume", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float MicVolume
    {
      get { return _MicVolume; }
      set { _MicVolume = value; }
    }

    private float _NomalPlayerVolume = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"NomalPlayerVolume", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float NomalPlayerVolume
    {
      get { return _NomalPlayerVolume; }
      set { _NomalPlayerVolume = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"subscribe_DJAni_msg")]
  public partial class subscribe_DJAni_msg : global::ProtoBuf.IExtensible
  {
    public subscribe_DJAni_msg() {}
    

    private int _AniType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AniType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AniType
    {
      get { return _AniType; }
      set { _AniType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}