//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/msg_4_room.proto
namespace ROOM_MSG
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VECTOR3")]
  public partial class VECTOR3 : global::ProtoBuf.IExtensible
  {
    public VECTOR3() {}
    
    private float _X;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"X", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float X
    {
      get { return _X; }
      set { _X = value; }
    }
    private float _Y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Y
    {
      get { return _Y; }
      set { _Y = value; }
    }
    private float _Z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Z
    {
      get { return _Z; }
      set { _Z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PLAYER_POS_INFO")]
  public partial class PLAYER_POS_INFO : global::ProtoBuf.IExtensible
  {
    public PLAYER_POS_INFO() {}
    
    private uint _PLAYER_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PLAYER_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PLAYER_ID
    {
      get { return _PLAYER_ID; }
      set { _PLAYER_ID = value; }
    }
    private ROOM_MSG.VECTOR3 _POS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"POS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ROOM_MSG.VECTOR3 POS
    {
      get { return _POS; }
      set { _POS = value; }
    }
    private ROOM_MSG.VECTOR3 _ROT;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ROT", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ROOM_MSG.VECTOR3 ROT
    {
      get { return _ROT; }
      set { _ROT = value; }
    }
    private ROOM_MSG.VECTOR3 _HAND_POS;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"HAND_POS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ROOM_MSG.VECTOR3 HAND_POS
    {
      get { return _HAND_POS; }
      set { _HAND_POS = value; }
    }
    private ROOM_MSG.VECTOR3 _HAND_ROT;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"HAND_ROT", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ROOM_MSG.VECTOR3 HAND_ROT
    {
      get { return _HAND_ROT; }
      set { _HAND_ROT = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PLAYER_INFO")]
  public partial class PLAYER_INFO : global::ProtoBuf.IExtensible
  {
    public PLAYER_INFO() {}
    
    private uint _PLAYER_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PLAYER_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PLAYER_ID
    {
      get { return _PLAYER_ID; }
      set { _PLAYER_ID = value; }
    }

    private string _PLAYER_NAME = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"PLAYER_NAME", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PLAYER_NAME
    {
      get { return _PLAYER_NAME; }
      set { _PLAYER_NAME = value; }
    }
    private uint _Characteristic;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Characteristic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Characteristic
    {
      get { return _Characteristic; }
      set { _Characteristic = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PLAYER_CHANGE")]
  public partial class PLAYER_CHANGE : global::ProtoBuf.IExtensible
  {
    public PLAYER_CHANGE() {}
    
    private ROOM_MSG.PLAYER_INFO _PLAYER;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PLAYER", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ROOM_MSG.PLAYER_INFO PLAYER
    {
      get { return _PLAYER; }
      set { _PLAYER = value; }
    }
    private ROOM_MSG.ROOM_PLAYERCHANGE_STATE _STATE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"STATE", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ROOM_MSG.ROOM_PLAYERCHANGE_STATE STATE
    {
      get { return _STATE; }
      set { _STATE = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_LEAVE_MSG")]
  public partial class CTS_LEAVE_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_LEAVE_MSG() {}
    
    private uint _ROOM_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ROOM_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ROOM_ID
    {
      get { return _ROOM_ID; }
      set { _ROOM_ID = value; }
    }
    private uint _STAGE_TYPE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"STAGE_TYPE", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint STAGE_TYPE
    {
      get { return _STAGE_TYPE; }
      set { _STAGE_TYPE = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_JOIN_MSG")]
  public partial class CTS_JOIN_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_JOIN_MSG() {}
    
    private uint _ROOM_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ROOM_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ROOM_ID
    {
      get { return _ROOM_ID; }
      set { _ROOM_ID = value; }
    }
    private uint _STAGE_TYPE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"STAGE_TYPE", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint STAGE_TYPE
    {
      get { return _STAGE_TYPE; }
      set { _STAGE_TYPE = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_JOIN_MSG")]
  public partial class STC_JOIN_MSG : global::ProtoBuf.IExtensible
  {
    public STC_JOIN_MSG() {}
    
    private ROOM_MSG.JOIN_RESULT _RESULT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RESULT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ROOM_MSG.JOIN_RESULT RESULT
    {
      get { return _RESULT; }
      set { _RESULT = value; }
    }

    private string _INFO = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string INFO
    {
      get { return _INFO; }
      set { _INFO = value; }
    }
    private uint _STAGE_TYPE;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"STAGE_TYPE", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint STAGE_TYPE
    {
      get { return _STAGE_TYPE; }
      set { _STAGE_TYPE = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_PLAYER_POS_MSG")]
  public partial class CTS_PLAYER_POS_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_PLAYER_POS_MSG() {}
    
    private uint _ROOM_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ROOM_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ROOM_ID
    {
      get { return _ROOM_ID; }
      set { _ROOM_ID = value; }
    }
    private ROOM_MSG.VECTOR3 _POS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"POS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ROOM_MSG.VECTOR3 POS
    {
      get { return _POS; }
      set { _POS = value; }
    }
    private ROOM_MSG.VECTOR3 _ROT;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ROT", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ROOM_MSG.VECTOR3 ROT
    {
      get { return _ROT; }
      set { _ROT = value; }
    }
    private ROOM_MSG.VECTOR3 _HAND_POS;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"HAND_POS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ROOM_MSG.VECTOR3 HAND_POS
    {
      get { return _HAND_POS; }
      set { _HAND_POS = value; }
    }
    private ROOM_MSG.VECTOR3 _HAND_ROT;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"HAND_ROT", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ROOM_MSG.VECTOR3 HAND_ROT
    {
      get { return _HAND_ROT; }
      set { _HAND_ROT = value; }
    }
    private uint _STAGE_TYPE;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"STAGE_TYPE", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint STAGE_TYPE
    {
      get { return _STAGE_TYPE; }
      set { _STAGE_TYPE = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_JOIN_READY_MSG")]
  public partial class CTS_JOIN_READY_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_JOIN_READY_MSG() {}
    
    private uint _ROOM_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ROOM_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ROOM_ID
    {
      get { return _ROOM_ID; }
      set { _ROOM_ID = value; }
    }
    private uint _STAGE_TYPE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"STAGE_TYPE", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint STAGE_TYPE
    {
      get { return _STAGE_TYPE; }
      set { _STAGE_TYPE = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_JOIN_READY_MSG")]
  public partial class STC_JOIN_READY_MSG : global::ProtoBuf.IExtensible
  {
    public STC_JOIN_READY_MSG() {}
    
    private ROOM_MSG.JOIN_RESULT _RESULT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RESULT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ROOM_MSG.JOIN_RESULT RESULT
    {
      get { return _RESULT; }
      set { _RESULT = value; }
    }

    private string _INFO = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string INFO
    {
      get { return _INFO; }
      set { _INFO = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_PLAYER_POS_CHANGE_NOTIFY_MSG")]
  public partial class STC_PLAYER_POS_CHANGE_NOTIFY_MSG : global::ProtoBuf.IExtensible
  {
    public STC_PLAYER_POS_CHANGE_NOTIFY_MSG() {}
    
    private readonly global::System.Collections.Generic.List<ROOM_MSG.PLAYER_POS_INFO> _LIST_PLAYER_POS = new global::System.Collections.Generic.List<ROOM_MSG.PLAYER_POS_INFO>();
    [global::ProtoBuf.ProtoMember(1, Name=@"LIST_PLAYER_POS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ROOM_MSG.PLAYER_POS_INFO> LIST_PLAYER_POS
    {
      get { return _LIST_PLAYER_POS; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_PLAYER_CHANGE_NOTIFY_MSG")]
  public partial class STC_PLAYER_CHANGE_NOTIFY_MSG : global::ProtoBuf.IExtensible
  {
    public STC_PLAYER_CHANGE_NOTIFY_MSG() {}
    
    private readonly global::System.Collections.Generic.List<ROOM_MSG.PLAYER_CHANGE> _LIST_PLAYER_CHANGE = new global::System.Collections.Generic.List<ROOM_MSG.PLAYER_CHANGE>();
    [global::ProtoBuf.ProtoMember(1, Name=@"LIST_PLAYER_CHANGE", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ROOM_MSG.PLAYER_CHANGE> LIST_PLAYER_CHANGE
    {
      get { return _LIST_PLAYER_CHANGE; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CMD_TYPE")]
    public enum CMD_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_TYPE_ROOM", Value=4)]
      MSG_TYPE_ROOM = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CMD_ID")]
    public enum CMD_ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_PLAYER_CHANGE_NOTIFY", Value=1)]
      STC_PLAYER_CHANGE_NOTIFY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_JOIN", Value=2)]
      CTS_JOIN = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_JOIN", Value=3)]
      STC_JOIN = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_LEAVE", Value=4)]
      CTS_LEAVE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_PLAYER_POS_CHANGE_NOTIFY", Value=101)]
      STC_PLAYER_POS_CHANGE_NOTIFY = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_PLAYER_POS", Value=102)]
      CTS_PLAYER_POS = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_JOIN_READY", Value=7)]
      STC_JOIN_READY = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_JOIN_READY", Value=8)]
      CTS_JOIN_READY = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"JOIN_RESULT")]
    public enum JOIN_RESULT
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAILED", Value=2)]
      FAILED = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ROOM_PLAYERCHANGE_STATE")]
    public enum ROOM_PLAYERCHANGE_STATE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"JOIN", Value=1)]
      JOIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEAVE", Value=2)]
      LEAVE = 2
    }
  
}