//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/msg_6_basketball.proto
namespace BASKETBALL_MSG
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VECTOR3")]
  public partial class VECTOR3 : global::ProtoBuf.IExtensible
  {
    public VECTOR3() {}
    
    private float _X;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"X", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float X
    {
      get { return _X; }
      set { _X = value; }
    }
    private float _Y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Y
    {
      get { return _Y; }
      set { _Y = value; }
    }
    private float _Z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Z
    {
      get { return _Z; }
      set { _Z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ROOM_INFO")]
  public partial class ROOM_INFO : global::ProtoBuf.IExtensible
  {
    public ROOM_INFO() {}
    
    private uint _ROOM_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ROOM_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ROOM_ID
    {
      get { return _ROOM_ID; }
      set { _ROOM_ID = value; }
    }
    private string _ROOM_OWNER_NAME;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ROOM_OWNER_NAME", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ROOM_OWNER_NAME
    {
      get { return _ROOM_OWNER_NAME; }
      set { _ROOM_OWNER_NAME = value; }
    }
    private uint _CURRENT_PLAYER_AMOUNT;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"CURRENT_PLAYER_AMOUNT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint CURRENT_PLAYER_AMOUNT
    {
      get { return _CURRENT_PLAYER_AMOUNT; }
      set { _CURRENT_PLAYER_AMOUNT = value; }
    }
    private uint _ALL_PLAYER_AMOUNT;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ALL_PLAYER_AMOUNT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ALL_PLAYER_AMOUNT
    {
      get { return _ALL_PLAYER_AMOUNT; }
      set { _ALL_PLAYER_AMOUNT = value; }
    }

    private uint _PRICE = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"PRICE", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint PRICE
    {
      get { return _PRICE; }
      set { _PRICE = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PLAYER_INFO")]
  public partial class PLAYER_INFO : global::ProtoBuf.IExtensible
  {
    public PLAYER_INFO() {}
    
    private uint _PLAYER_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PLAYER_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PLAYER_ID
    {
      get { return _PLAYER_ID; }
      set { _PLAYER_ID = value; }
    }

    private uint _PLAYER_INDEX = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"PLAYER_INDEX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint PLAYER_INDEX
    {
      get { return _PLAYER_INDEX; }
      set { _PLAYER_INDEX = value; }
    }

    private string _PLAYER_NAME = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"PLAYER_NAME", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PLAYER_NAME
    {
      get { return _PLAYER_NAME; }
      set { _PLAYER_NAME = value; }
    }
    private uint _Characteristic;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Characteristic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Characteristic
    {
      get { return _Characteristic; }
      set { _Characteristic = value; }
    }
    private BASKETBALL_MSG.PLAYER_STATE _STATE;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"STATE", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BASKETBALL_MSG.PLAYER_STATE STATE
    {
      get { return _STATE; }
      set { _STATE = value; }
    }

    private BASKETBALL_MSG.PLAYER_RANK _RANK = BASKETBALL_MSG.PLAYER_RANK.ROOKIE;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"RANK", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(BASKETBALL_MSG.PLAYER_RANK.ROOKIE)]
    public BASKETBALL_MSG.PLAYER_RANK RANK
    {
      get { return _RANK; }
      set { _RANK = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PLAYER_BASIC_INFO")]
  public partial class PLAYER_BASIC_INFO : global::ProtoBuf.IExtensible
  {
    public PLAYER_BASIC_INFO() {}
    
    private uint _PLAYER_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PLAYER_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PLAYER_ID
    {
      get { return _PLAYER_ID; }
      set { _PLAYER_ID = value; }
    }

    private string _PLAYER_NAME = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"PLAYER_NAME", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PLAYER_NAME
    {
      get { return _PLAYER_NAME; }
      set { _PLAYER_NAME = value; }
    }
    private uint _Characteristic;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Characteristic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Characteristic
    {
      get { return _Characteristic; }
      set { _Characteristic = value; }
    }
    private uint _GOLD;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"GOLD", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint GOLD
    {
      get { return _GOLD; }
      set { _GOLD = value; }
    }
    private BASKETBALL_MSG.PLAYER_RANK _RANK;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"RANK", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BASKETBALL_MSG.PLAYER_RANK RANK
    {
      get { return _RANK; }
      set { _RANK = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PLAYER_POS_INFO")]
  public partial class PLAYER_POS_INFO : global::ProtoBuf.IExtensible
  {
    public PLAYER_POS_INFO() {}
    
    private uint _PLAYER_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PLAYER_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PLAYER_ID
    {
      get { return _PLAYER_ID; }
      set { _PLAYER_ID = value; }
    }
    private BASKETBALL_MSG.VECTOR3 _POS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"POS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public BASKETBALL_MSG.VECTOR3 POS
    {
      get { return _POS; }
      set { _POS = value; }
    }
    private BASKETBALL_MSG.VECTOR3 _ROT;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ROT", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public BASKETBALL_MSG.VECTOR3 ROT
    {
      get { return _ROT; }
      set { _ROT = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PLAYER_READY_STATE")]
  public partial class PLAYER_READY_STATE : global::ProtoBuf.IExtensible
  {
    public PLAYER_READY_STATE() {}
    
    private BASKETBALL_MSG.PLAYER_STATE _STATE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"STATE", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BASKETBALL_MSG.PLAYER_STATE STATE
    {
      get { return _STATE; }
      set { _STATE = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PLAYER_SHOOT_INFO")]
  public partial class PLAYER_SHOOT_INFO : global::ProtoBuf.IExtensible
  {
    public PLAYER_SHOOT_INFO() {}
    
    private uint _PLAYER_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PLAYER_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PLAYER_ID
    {
      get { return _PLAYER_ID; }
      set { _PLAYER_ID = value; }
    }
    private uint _PLAYER_SHOOT;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"PLAYER_SHOOT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PLAYER_SHOOT
    {
      get { return _PLAYER_SHOOT; }
      set { _PLAYER_SHOOT = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PLAYER_SCORE_INFO")]
  public partial class PLAYER_SCORE_INFO : global::ProtoBuf.IExtensible
  {
    public PLAYER_SCORE_INFO() {}
    
    private uint _PLAYER;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PLAYER", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PLAYER
    {
      get { return _PLAYER; }
      set { _PLAYER = value; }
    }
    private uint _PLAYER_SCORE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"PLAYER_SCORE", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PLAYER_SCORE
    {
      get { return _PLAYER_SCORE; }
      set { _PLAYER_SCORE = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BALL_INFO")]
  public partial class BALL_INFO : global::ProtoBuf.IExtensible
  {
    public BALL_INFO() {}
    
    private BASKETBALL_MSG.VECTOR3 _POS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"POS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public BASKETBALL_MSG.VECTOR3 POS
    {
      get { return _POS; }
      set { _POS = value; }
    }
    private BASKETBALL_MSG.VECTOR3 _DIRECTION;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"DIRECTION", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public BASKETBALL_MSG.VECTOR3 DIRECTION
    {
      get { return _DIRECTION; }
      set { _DIRECTION = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GAME_INFO")]
  public partial class GAME_INFO : global::ProtoBuf.IExtensible
  {
    public GAME_INFO() {}
    
    private uint _PLAYER_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PLAYER_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PLAYER_ID
    {
      get { return _PLAYER_ID; }
      set { _PLAYER_ID = value; }
    }

    private string _PLAYER_NAME = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"PLAYER_NAME", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PLAYER_NAME
    {
      get { return _PLAYER_NAME; }
      set { _PLAYER_NAME = value; }
    }
    private uint _PLAYER_SCORE;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"PLAYER_SCORE", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PLAYER_SCORE
    {
      get { return _PLAYER_SCORE; }
      set { _PLAYER_SCORE = value; }
    }
    private uint _PLAYER_ACCOUNT_CREDITS;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"PLAYER_ACCOUNT_CREDITS", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PLAYER_ACCOUNT_CREDITS
    {
      get { return _PLAYER_ACCOUNT_CREDITS; }
      set { _PLAYER_ACCOUNT_CREDITS = value; }
    }
    private uint _PLAYER_GAME_CREDITS;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"PLAYER_GAME_CREDITS", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PLAYER_GAME_CREDITS
    {
      get { return _PLAYER_GAME_CREDITS; }
      set { _PLAYER_GAME_CREDITS = value; }
    }
    private uint _PLAYER_ACCOUNT_GOLD;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"PLAYER_ACCOUNT_GOLD", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PLAYER_ACCOUNT_GOLD
    {
      get { return _PLAYER_ACCOUNT_GOLD; }
      set { _PLAYER_ACCOUNT_GOLD = value; }
    }
    private uint _PLAYER_GAME_GOLD;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"PLAYER_GAME_GOLD", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PLAYER_GAME_GOLD
    {
      get { return _PLAYER_GAME_GOLD; }
      set { _PLAYER_GAME_GOLD = value; }
    }
    private BASKETBALL_MSG.PLAYER_RANK _RANK;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"RANK", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BASKETBALL_MSG.PLAYER_RANK RANK
    {
      get { return _RANK; }
      set { _RANK = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_ENTER_BASKETBALL_MSG")]
  public partial class STC_ENTER_BASKETBALL_MSG : global::ProtoBuf.IExtensible
  {
    public STC_ENTER_BASKETBALL_MSG() {}
    
    private BASKETBALL_MSG.ACTION_RESULT _RESULT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RESULT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BASKETBALL_MSG.ACTION_RESULT RESULT
    {
      get { return _RESULT; }
      set { _RESULT = value; }
    }

    private string _INFO = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string INFO
    {
      get { return _INFO; }
      set { _INFO = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_CREATE_ROOM_MSG")]
  public partial class CTS_CREATE_ROOM_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_CREATE_ROOM_MSG() {}
    
    private uint _PLAYER_AMOUNT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PLAYER_AMOUNT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PLAYER_AMOUNT
    {
      get { return _PLAYER_AMOUNT; }
      set { _PLAYER_AMOUNT = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_CREATE_ROOM_MSG")]
  public partial class STC_CREATE_ROOM_MSG : global::ProtoBuf.IExtensible
  {
    public STC_CREATE_ROOM_MSG() {}
    
    private BASKETBALL_MSG.ROOM_INFO _CURRENT_ROOM_INFO;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"CURRENT_ROOM_INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public BASKETBALL_MSG.ROOM_INFO CURRENT_ROOM_INFO
    {
      get { return _CURRENT_ROOM_INFO; }
      set { _CURRENT_ROOM_INFO = value; }
    }
    private BASKETBALL_MSG.ACTION_RESULT _RESULT;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RESULT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BASKETBALL_MSG.ACTION_RESULT RESULT
    {
      get { return _RESULT; }
      set { _RESULT = value; }
    }

    private string _INFO = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string INFO
    {
      get { return _INFO; }
      set { _INFO = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_LEAVE_ROOM_MSG")]
  public partial class CTS_LEAVE_ROOM_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_LEAVE_ROOM_MSG() {}
    
    private uint _ROOM_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ROOM_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ROOM_ID
    {
      get { return _ROOM_ID; }
      set { _ROOM_ID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_LEAVE_ROOM_MSG")]
  public partial class STC_LEAVE_ROOM_MSG : global::ProtoBuf.IExtensible
  {
    public STC_LEAVE_ROOM_MSG() {}
    
    private BASKETBALL_MSG.ACTION_RESULT _RESULT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RESULT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BASKETBALL_MSG.ACTION_RESULT RESULT
    {
      get { return _RESULT; }
      set { _RESULT = value; }
    }

    private string _INFO = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string INFO
    {
      get { return _INFO; }
      set { _INFO = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_JOIN_ROOM_MSG")]
  public partial class CTS_JOIN_ROOM_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_JOIN_ROOM_MSG() {}
    
    private uint _ROOM_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ROOM_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ROOM_ID
    {
      get { return _ROOM_ID; }
      set { _ROOM_ID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_JOIN_ROOM_MSG")]
  public partial class STC_JOIN_ROOM_MSG : global::ProtoBuf.IExtensible
  {
    public STC_JOIN_ROOM_MSG() {}
    
    private BASKETBALL_MSG.ACTION_RESULT _RESULT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RESULT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BASKETBALL_MSG.ACTION_RESULT RESULT
    {
      get { return _RESULT; }
      set { _RESULT = value; }
    }

    private string _INFO = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string INFO
    {
      get { return _INFO; }
      set { _INFO = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_READY_STATE_MSG")]
  public partial class CTS_READY_STATE_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_READY_STATE_MSG() {}
    
    private BASKETBALL_MSG.PLAYER_STATE _STATE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"STATE", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BASKETBALL_MSG.PLAYER_STATE STATE
    {
      get { return _STATE; }
      set { _STATE = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_READY_STATE_MSG")]
  public partial class STC_READY_STATE_MSG : global::ProtoBuf.IExtensible
  {
    public STC_READY_STATE_MSG() {}
    
    private readonly global::System.Collections.Generic.List<BASKETBALL_MSG.PLAYER_INFO> _LIST_PLAYER_INFO = new global::System.Collections.Generic.List<BASKETBALL_MSG.PLAYER_INFO>();
    [global::ProtoBuf.ProtoMember(1, Name=@"LIST_PLAYER_INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BASKETBALL_MSG.PLAYER_INFO> LIST_PLAYER_INFO
    {
      get { return _LIST_PLAYER_INFO; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_KICK_PLAYER_MSG")]
  public partial class CTS_KICK_PLAYER_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_KICK_PLAYER_MSG() {}
    
    private uint _PLAYER_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PLAYER_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PLAYER_ID
    {
      get { return _PLAYER_ID; }
      set { _PLAYER_ID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_KICK_PLAYER_MSG")]
  public partial class STC_KICK_PLAYER_MSG : global::ProtoBuf.IExtensible
  {
    public STC_KICK_PLAYER_MSG() {}
    
    private BASKETBALL_MSG.ACTION_RESULT _RESULT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RESULT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BASKETBALL_MSG.ACTION_RESULT RESULT
    {
      get { return _RESULT; }
      set { _RESULT = value; }
    }

    private string _INFO = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string INFO
    {
      get { return _INFO; }
      set { _INFO = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_KICK_NOTIFY_MSG")]
  public partial class STC_KICK_NOTIFY_MSG : global::ProtoBuf.IExtensible
  {
    public STC_KICK_NOTIFY_MSG() {}
    
    private BASKETBALL_MSG.ACTION_RESULT _RESULT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RESULT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BASKETBALL_MSG.ACTION_RESULT RESULT
    {
      get { return _RESULT; }
      set { _RESULT = value; }
    }

    private string _INFO = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string INFO
    {
      get { return _INFO; }
      set { _INFO = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_ALL_READY_START_MSG")]
  public partial class CTS_ALL_READY_START_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_ALL_READY_START_MSG() {}
    
    private uint _ROOM_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ROOM_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ROOM_ID
    {
      get { return _ROOM_ID; }
      set { _ROOM_ID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_ALL_READY_START_MSG")]
  public partial class STC_ALL_READY_START_MSG : global::ProtoBuf.IExtensible
  {
    public STC_ALL_READY_START_MSG() {}
    
    private BASKETBALL_MSG.ACTION_RESULT _RESULT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RESULT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BASKETBALL_MSG.ACTION_RESULT RESULT
    {
      get { return _RESULT; }
      set { _RESULT = value; }
    }

    private string _INFO = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string INFO
    {
      get { return _INFO; }
      set { _INFO = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_START_STATE_MSG")]
  public partial class STC_START_STATE_MSG : global::ProtoBuf.IExtensible
  {
    public STC_START_STATE_MSG() {}
    
    private BASKETBALL_MSG.ACTION_RESULT _RESULT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RESULT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BASKETBALL_MSG.ACTION_RESULT RESULT
    {
      get { return _RESULT; }
      set { _RESULT = value; }
    }

    private string _INFO = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string INFO
    {
      get { return _INFO; }
      set { _INFO = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_PLAYER_SHOOT_MSG")]
  public partial class CTS_PLAYER_SHOOT_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_PLAYER_SHOOT_MSG() {}
    
    private BASKETBALL_MSG.PLAYER_SHOOT_INFO _SHOOT_INFO;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SHOOT_INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public BASKETBALL_MSG.PLAYER_SHOOT_INFO SHOOT_INFO
    {
      get { return _SHOOT_INFO; }
      set { _SHOOT_INFO = value; }
    }
    private BASKETBALL_MSG.BALL_INFO _PLAYER_BALL_INFO;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"PLAYER_BALL_INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public BASKETBALL_MSG.BALL_INFO PLAYER_BALL_INFO
    {
      get { return _PLAYER_BALL_INFO; }
      set { _PLAYER_BALL_INFO = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_PLAYER_SHOOT_MSG")]
  public partial class STC_PLAYER_SHOOT_MSG : global::ProtoBuf.IExtensible
  {
    public STC_PLAYER_SHOOT_MSG() {}
    
    private BASKETBALL_MSG.PLAYER_SHOOT_INFO _SHOOT_INFO;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SHOOT_INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public BASKETBALL_MSG.PLAYER_SHOOT_INFO SHOOT_INFO
    {
      get { return _SHOOT_INFO; }
      set { _SHOOT_INFO = value; }
    }
    private BASKETBALL_MSG.BALL_INFO _PLAYER_BALL_INFO;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"PLAYER_BALL_INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public BASKETBALL_MSG.BALL_INFO PLAYER_BALL_INFO
    {
      get { return _PLAYER_BALL_INFO; }
      set { _PLAYER_BALL_INFO = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_PLAYER_SCORE_MSG")]
  public partial class CTS_PLAYER_SCORE_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_PLAYER_SCORE_MSG() {}
    
    private BASKETBALL_MSG.PLAYER_SCORE_INFO _SCORE_INFO;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SCORE_INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public BASKETBALL_MSG.PLAYER_SCORE_INFO SCORE_INFO
    {
      get { return _SCORE_INFO; }
      set { _SCORE_INFO = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_PLAYER_SCORE_MSG")]
  public partial class STC_PLAYER_SCORE_MSG : global::ProtoBuf.IExtensible
  {
    public STC_PLAYER_SCORE_MSG() {}
    
    private readonly global::System.Collections.Generic.List<BASKETBALL_MSG.PLAYER_SCORE_INFO> _LIST_SCORE_INFO = new global::System.Collections.Generic.List<BASKETBALL_MSG.PLAYER_SCORE_INFO>();
    [global::ProtoBuf.ProtoMember(1, Name=@"LIST_SCORE_INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BASKETBALL_MSG.PLAYER_SCORE_INFO> LIST_SCORE_INFO
    {
      get { return _LIST_SCORE_INFO; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_GAME_OVER_MSG")]
  public partial class STC_GAME_OVER_MSG : global::ProtoBuf.IExtensible
  {
    public STC_GAME_OVER_MSG() {}
    
    private readonly global::System.Collections.Generic.List<BASKETBALL_MSG.GAME_INFO> _LIST_GAME_INFO = new global::System.Collections.Generic.List<BASKETBALL_MSG.GAME_INFO>();
    [global::ProtoBuf.ProtoMember(1, Name=@"LIST_GAME_INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BASKETBALL_MSG.GAME_INFO> LIST_GAME_INFO
    {
      get { return _LIST_GAME_INFO; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_PLAYER_POS_MSG")]
  public partial class CTS_PLAYER_POS_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_PLAYER_POS_MSG() {}
    
    private BASKETBALL_MSG.PLAYER_POS_INFO _PLAYER_POS_DATE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PLAYER_POS_DATE", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public BASKETBALL_MSG.PLAYER_POS_INFO PLAYER_POS_DATE
    {
      get { return _PLAYER_POS_DATE; }
      set { _PLAYER_POS_DATE = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_PLAYER_POS_MSG")]
  public partial class STC_PLAYER_POS_MSG : global::ProtoBuf.IExtensible
  {
    public STC_PLAYER_POS_MSG() {}
    
    private readonly global::System.Collections.Generic.List<BASKETBALL_MSG.PLAYER_POS_INFO> _LIST_PLAYER_POS = new global::System.Collections.Generic.List<BASKETBALL_MSG.PLAYER_POS_INFO>();
    [global::ProtoBuf.ProtoMember(1, Name=@"LIST_PLAYER_POS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BASKETBALL_MSG.PLAYER_POS_INFO> LIST_PLAYER_POS
    {
      get { return _LIST_PLAYER_POS; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_PLAYER_LIST_MSG")]
  public partial class STC_PLAYER_LIST_MSG : global::ProtoBuf.IExtensible
  {
    public STC_PLAYER_LIST_MSG() {}
    
    private uint _ROOM_OWNER_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ROOM_OWNER_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ROOM_OWNER_ID
    {
      get { return _ROOM_OWNER_ID; }
      set { _ROOM_OWNER_ID = value; }
    }
    private readonly global::System.Collections.Generic.List<BASKETBALL_MSG.PLAYER_INFO> _LIST_PLAYER_INFO = new global::System.Collections.Generic.List<BASKETBALL_MSG.PLAYER_INFO>();
    [global::ProtoBuf.ProtoMember(2, Name=@"LIST_PLAYER_INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BASKETBALL_MSG.PLAYER_INFO> LIST_PLAYER_INFO
    {
      get { return _LIST_PLAYER_INFO; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_ROOM_LIST_MSG")]
  public partial class STC_ROOM_LIST_MSG : global::ProtoBuf.IExtensible
  {
    public STC_ROOM_LIST_MSG() {}
    
    private readonly global::System.Collections.Generic.List<BASKETBALL_MSG.ROOM_INFO> _LIST_ROOM_INFO = new global::System.Collections.Generic.List<BASKETBALL_MSG.ROOM_INFO>();
    [global::ProtoBuf.ProtoMember(1, Name=@"LIST_ROOM_INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BASKETBALL_MSG.ROOM_INFO> LIST_ROOM_INFO
    {
      get { return _LIST_ROOM_INFO; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_PLAYER_START_POS_MSG")]
  public partial class CTS_PLAYER_START_POS_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_PLAYER_START_POS_MSG() {}
    
    private readonly global::System.Collections.Generic.List<BASKETBALL_MSG.VECTOR3> _START_POS = new global::System.Collections.Generic.List<BASKETBALL_MSG.VECTOR3>();
    [global::ProtoBuf.ProtoMember(1, Name=@"START_POS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BASKETBALL_MSG.VECTOR3> START_POS
    {
      get { return _START_POS; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_PLAYER_START_POS_MSG")]
  public partial class STC_PLAYER_START_POS_MSG : global::ProtoBuf.IExtensible
  {
    public STC_PLAYER_START_POS_MSG() {}
    
    private readonly global::System.Collections.Generic.List<BASKETBALL_MSG.VECTOR3> _START_POS = new global::System.Collections.Generic.List<BASKETBALL_MSG.VECTOR3>();
    [global::ProtoBuf.ProtoMember(1, Name=@"START_POS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BASKETBALL_MSG.VECTOR3> START_POS
    {
      get { return _START_POS; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_PLAYER_INFO_MSG")]
  public partial class STC_PLAYER_INFO_MSG : global::ProtoBuf.IExtensible
  {
    public STC_PLAYER_INFO_MSG() {}
    
    private BASKETBALL_MSG.PLAYER_BASIC_INFO _PLAYER_SELF;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PLAYER_SELF", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public BASKETBALL_MSG.PLAYER_BASIC_INFO PLAYER_SELF
    {
      get { return _PLAYER_SELF; }
      set { _PLAYER_SELF = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_EXIT_GAME_MSG")]
  public partial class STC_EXIT_GAME_MSG : global::ProtoBuf.IExtensible
  {
    public STC_EXIT_GAME_MSG() {}
    
    private BASKETBALL_MSG.ACTION_RESULT _RESULT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RESULT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BASKETBALL_MSG.ACTION_RESULT RESULT
    {
      get { return _RESULT; }
      set { _RESULT = value; }
    }

    private string _INFO = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string INFO
    {
      get { return _INFO; }
      set { _INFO = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CMD_TYPE")]
    public enum CMD_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_TYPE_BASKETBALL", Value=6)]
      MSG_TYPE_BASKETBALL = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CMD_ID")]
    public enum CMD_ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_ENTER_BASKETBALL", Value=1)]
      CTS_ENTER_BASKETBALL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_ENTER_BASKETBALL", Value=2)]
      STC_ENTER_BASKETBALL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_CREATE_ROOM", Value=3)]
      CTS_CREATE_ROOM = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_CREATE_ROOM", Value=4)]
      STC_CREATE_ROOM = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_LEAVE_ROOM", Value=5)]
      CTS_LEAVE_ROOM = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_LEAVE_ROOM", Value=6)]
      STC_LEAVE_ROOM = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_JOIN_ROOM", Value=7)]
      CTS_JOIN_ROOM = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_JOIN_ROOM", Value=8)]
      STC_JOIN_ROOM = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_READY_STATE", Value=9)]
      CTS_READY_STATE = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_READY_STATE", Value=10)]
      STC_READY_STATE = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_KICK_PLAYER", Value=11)]
      CTS_KICK_PLAYER = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_KICK_PLAYER", Value=12)]
      STC_KICK_PLAYER = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_KICK_NOTIFY", Value=13)]
      STC_KICK_NOTIFY = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_ALL_READY_START", Value=14)]
      CTS_ALL_READY_START = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_ALL_READY_START", Value=15)]
      STC_ALL_READY_START = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_START_STATE", Value=16)]
      CTS_START_STATE = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_START_STATE", Value=17)]
      STC_START_STATE = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_PLAYER_SHOOT", Value=20)]
      CTS_PLAYER_SHOOT = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_PLAYER_SHOOT", Value=21)]
      STC_PLAYER_SHOOT = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_PLAYER_SCORE", Value=22)]
      CTS_PLAYER_SCORE = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_PLAYER_SCORE", Value=23)]
      STC_PLAYER_SCORE = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_GAME_OVER", Value=24)]
      CTS_GAME_OVER = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_GAME_OVER", Value=25)]
      STC_GAME_OVER = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_PLAYER_LIST", Value=28)]
      CTS_PLAYER_LIST = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_PLAYER_LIST", Value=29)]
      STC_PLAYER_LIST = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_ROOM_LIST", Value=30)]
      CTS_ROOM_LIST = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_ROOM_LIST", Value=31)]
      STC_ROOM_LIST = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_PLAYER_START_POS", Value=32)]
      CTS_PLAYER_START_POS = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_PLAYER_START_POS", Value=33)]
      STC_PLAYER_START_POS = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_PLAYER_INFO", Value=34)]
      CTS_PLAYER_INFO = 34,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_PLAYER_INFO", Value=35)]
      STC_PLAYER_INFO = 35,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_EXIT_GAME", Value=36)]
      CTS_EXIT_GAME = 36,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_EXIT_GAME", Value=37)]
      STC_EXIT_GAME = 37,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_PLAYER_POS", Value=101)]
      CTS_PLAYER_POS = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_PLAYER_POS", Value=102)]
      STC_PLAYER_POS = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_BALL_POS", Value=103)]
      CTS_BALL_POS = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_BALL_POS", Value=104)]
      STC_BALL_POS = 104
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ACTION_RESULT")]
    public enum ACTION_RESULT
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAILED", Value=2)]
      FAILED = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PLAYER_STATE")]
    public enum PLAYER_STATE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"READY", Value=1)]
      READY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_READY", Value=2)]
      NOT_READY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEAVE", Value=3)]
      LEAVE = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PLAYER_RANK")]
    public enum PLAYER_RANK
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROOKIE", Value=1)]
      ROOKIE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PRO", Value=2)]
      PRO = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALL_STAR", Value=3)]
      ALL_STAR = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUPER_STAR", Value=4)]
      SUPER_STAR = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HALL_OF_FAME", Value=5)]
      HALL_OF_FAME = 5
    }
  
}