//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/msg_8_friend.proto
namespace FRIEND_MSG
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendInfo")]
  public partial class FriendInfo : global::ProtoBuf.IExtensible
  {
    public FriendInfo() {}
    
    private uint _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _Characteristic;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Characteristic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Characteristic
    {
      get { return _Characteristic; }
      set { _Characteristic = value; }
    }
    private FRIEND_MSG.RELATION_TYPE _relation;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"relation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public FRIEND_MSG.RELATION_TYPE relation
    {
      get { return _relation; }
      set { _relation = value; }
    }
    private ulong _offLineTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"offLineTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong offLineTime
    {
      get { return _offLineTime; }
      set { _offLineTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_FRIEND_LIST_MSG")]
  public partial class STC_FRIEND_LIST_MSG : global::ProtoBuf.IExtensible
  {
    public STC_FRIEND_LIST_MSG() {}
    
    private readonly global::System.Collections.Generic.List<FRIEND_MSG.FriendInfo> _friendsList = new global::System.Collections.Generic.List<FRIEND_MSG.FriendInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"friendsList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FRIEND_MSG.FriendInfo> friendsList
    {
      get { return _friendsList; }
    }
  
    private readonly global::System.Collections.Generic.List<FRIEND_MSG.FriendInfo> _applyList = new global::System.Collections.Generic.List<FRIEND_MSG.FriendInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"applyList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FRIEND_MSG.FriendInfo> applyList
    {
      get { return _applyList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_FRIEND_APPLY_MSG")]
  public partial class CTS_FRIEND_APPLY_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_FRIEND_APPLY_MSG() {}
    
    private uint _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_FRIEND_APPLY_MSG")]
  public partial class STC_FRIEND_APPLY_MSG : global::ProtoBuf.IExtensible
  {
    public STC_FRIEND_APPLY_MSG() {}
    
    private FRIEND_MSG.RESULT_TYPE _success;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public FRIEND_MSG.RESULT_TYPE success
    {
      get { return _success; }
      set { _success = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_FRIEND_CONFIRM_MSG")]
  public partial class CTS_FRIEND_CONFIRM_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_FRIEND_CONFIRM_MSG() {}
    
    private uint _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private FRIEND_MSG.RESULT_TYPE _isAgree;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isAgree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public FRIEND_MSG.RESULT_TYPE isAgree
    {
      get { return _isAgree; }
      set { _isAgree = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_FRIEND_CONFIRM_MSG")]
  public partial class STC_FRIEND_CONFIRM_MSG : global::ProtoBuf.IExtensible
  {
    public STC_FRIEND_CONFIRM_MSG() {}
    
    private uint _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private FRIEND_MSG.RESULT_TYPE _isAgree;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isAgree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public FRIEND_MSG.RESULT_TYPE isAgree
    {
      get { return _isAgree; }
      set { _isAgree = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_FRIEND_DELETE_MSG")]
  public partial class CTS_FRIEND_DELETE_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_FRIEND_DELETE_MSG() {}
    
    private uint _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_FRIEND_DELETE_MSG")]
  public partial class STC_FRIEND_DELETE_MSG : global::ProtoBuf.IExtensible
  {
    public STC_FRIEND_DELETE_MSG() {}
    
    private uint _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private FRIEND_MSG.RESULT_TYPE _success;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public FRIEND_MSG.RESULT_TYPE success
    {
      get { return _success; }
      set { _success = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_FRIEND_BLACK_MSG")]
  public partial class CTS_FRIEND_BLACK_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_FRIEND_BLACK_MSG() {}
    
    private uint _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_FRIEND_BLACK_MSG")]
  public partial class STC_FRIEND_BLACK_MSG : global::ProtoBuf.IExtensible
  {
    public STC_FRIEND_BLACK_MSG() {}
    
    private FRIEND_MSG.FriendInfo _info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public FRIEND_MSG.FriendInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private FRIEND_MSG.RESULT_TYPE _success;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public FRIEND_MSG.RESULT_TYPE success
    {
      get { return _success; }
      set { _success = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_FRIEND_REMOVE_BLACK_MSG")]
  public partial class CTS_FRIEND_REMOVE_BLACK_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_FRIEND_REMOVE_BLACK_MSG() {}
    
    private uint _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_FRIEND_REMOVE_BLACK_MSG")]
  public partial class STC_FRIEND_REMOVE_BLACK_MSG : global::ProtoBuf.IExtensible
  {
    public STC_FRIEND_REMOVE_BLACK_MSG() {}
    
    private uint _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private FRIEND_MSG.RESULT_TYPE _success;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public FRIEND_MSG.RESULT_TYPE success
    {
      get { return _success; }
      set { _success = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_FRIEND_MASK_MSG")]
  public partial class CTS_FRIEND_MASK_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_FRIEND_MASK_MSG() {}
    
    private uint _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_FRIEND_MASK_MSG")]
  public partial class STC_FRIEND_MASK_MSG : global::ProtoBuf.IExtensible
  {
    public STC_FRIEND_MASK_MSG() {}
    
    private uint _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private FRIEND_MSG.RESULT_TYPE _success;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public FRIEND_MSG.RESULT_TYPE success
    {
      get { return _success; }
      set { _success = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_FRIEND_UNMASK_MSG")]
  public partial class CTS_FRIEND_UNMASK_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_FRIEND_UNMASK_MSG() {}
    
    private uint _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_FRIEND_UNMASK_MSG")]
  public partial class STC_FRIEND_UNMASK_MSG : global::ProtoBuf.IExtensible
  {
    public STC_FRIEND_UNMASK_MSG() {}
    
    private uint _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private FRIEND_MSG.RESULT_TYPE _success;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public FRIEND_MSG.RESULT_TYPE success
    {
      get { return _success; }
      set { _success = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_FRIEND_AGREE_ALL_MSG")]
  public partial class CTS_FRIEND_AGREE_ALL_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_FRIEND_AGREE_ALL_MSG() {}
    
    private uint _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_FRIEND_AGREE_ALL_MSG")]
  public partial class STC_FRIEND_AGREE_ALL_MSG : global::ProtoBuf.IExtensible
  {
    public STC_FRIEND_AGREE_ALL_MSG() {}
    
    private FRIEND_MSG.RESULT_TYPE _success;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public FRIEND_MSG.RESULT_TYPE success
    {
      get { return _success; }
      set { _success = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_FRIEND_REFUSE_ALL_MSG")]
  public partial class CTS_FRIEND_REFUSE_ALL_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_FRIEND_REFUSE_ALL_MSG() {}
    
    private uint _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_FRIEND_REFUSE_ALL_MSG")]
  public partial class STC_FRIEND_REFUSE_ALL_MSG : global::ProtoBuf.IExtensible
  {
    public STC_FRIEND_REFUSE_ALL_MSG() {}
    
    private FRIEND_MSG.RESULT_TYPE _success;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public FRIEND_MSG.RESULT_TYPE success
    {
      get { return _success; }
      set { _success = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_FRIEND_PUSH_NOTIFY_MSG")]
  public partial class STC_FRIEND_PUSH_NOTIFY_MSG : global::ProtoBuf.IExtensible
  {
    public STC_FRIEND_PUSH_NOTIFY_MSG() {}
    
    private FRIEND_MSG.FriendInfo _friendInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"friendInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public FRIEND_MSG.FriendInfo friendInfo
    {
      get { return _friendInfo; }
      set { _friendInfo = value; }
    }
    private FRIEND_MSG.NOTIFY_TYPE _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public FRIEND_MSG.NOTIFY_TYPE type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_ROLE_INFO_MSG")]
  public partial class CTS_ROLE_INFO_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_ROLE_INFO_MSG() {}
    
    private uint _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_ROLE_INFO_MSG")]
  public partial class STC_ROLE_INFO_MSG : global::ProtoBuf.IExtensible
  {
    public STC_ROLE_INFO_MSG() {}
    
    private uint _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _Characteristic;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Characteristic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Characteristic
    {
      get { return _Characteristic; }
      set { _Characteristic = value; }
    }
    private string _sign;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"sign", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sign
    {
      get { return _sign; }
      set { _sign = value; }
    }
    private string _home;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"home", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string home
    {
      get { return _home; }
      set { _home = value; }
    }
    private string _job;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string job
    {
      get { return _job; }
      set { _job = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_FRIEND_SEARCH_MSG")]
  public partial class CTS_FRIEND_SEARCH_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_FRIEND_SEARCH_MSG() {}
    
    private string _idstr;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"idstr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string idstr
    {
      get { return _idstr; }
      set { _idstr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_FRIEND_SEARCH_MSG")]
  public partial class STC_FRIEND_SEARCH_MSG : global::ProtoBuf.IExtensible
  {
    public STC_FRIEND_SEARCH_MSG() {}
    
    private FRIEND_MSG.RESULT_TYPE _RESULT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RESULT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public FRIEND_MSG.RESULT_TYPE RESULT
    {
      get { return _RESULT; }
      set { _RESULT = value; }
    }

    private string _INFO = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string INFO
    {
      get { return _INFO; }
      set { _INFO = value; }
    }

    private FRIEND_MSG.FriendInfo _friendsInfo = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"friendsInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FRIEND_MSG.FriendInfo friendsInfo
    {
      get { return _friendsInfo; }
      set { _friendsInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CMD_TYPE")]
    public enum CMD_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_TYPE_FRIEND", Value=8)]
      MSG_TYPE_FRIEND = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CMD_ID")]
    public enum CMD_ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_FRIEND_LIST", Value=1)]
      CTS_FRIEND_LIST = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_FRIEND_LIST", Value=2)]
      STC_FRIEND_LIST = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_FRIEND_APPLY", Value=3)]
      CTS_FRIEND_APPLY = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_FRIEND_APPLY", Value=4)]
      STC_FRIEND_APPLY = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_FRIEND_CONFIRM", Value=5)]
      CTS_FRIEND_CONFIRM = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_FRIEND_CONFIRM", Value=6)]
      STC_FRIEND_CONFIRM = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_FRIEND_DELETE", Value=7)]
      CTS_FRIEND_DELETE = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_FRIEND_DELETE", Value=8)]
      STC_FRIEND_DELETE = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_FRIEND_BLACK", Value=9)]
      CTS_FRIEND_BLACK = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_FRIEND_BLACK", Value=10)]
      STC_FRIEND_BLACK = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_FRIEND_REMOVE_BLACK", Value=11)]
      CTS_FRIEND_REMOVE_BLACK = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_FRIEND_REMOVE_BLACK", Value=12)]
      STC_FRIEND_REMOVE_BLACK = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_FRIEND_MASK", Value=13)]
      CTS_FRIEND_MASK = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_FRIEND_MASK", Value=14)]
      STC_FRIEND_MASK = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_FRIEND_UNMASK", Value=15)]
      CTS_FRIEND_UNMASK = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_FRIEND_UNMASK", Value=16)]
      STC_FRIEND_UNMASK = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_FRIEND_PUSH_NOTIFY", Value=17)]
      STC_FRIEND_PUSH_NOTIFY = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_ROLE_INFO", Value=18)]
      CTS_ROLE_INFO = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_ROLE_INFO", Value=19)]
      STC_ROLE_INFO = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_FRIEND_AGREE_ALL", Value=20)]
      CTS_FRIEND_AGREE_ALL = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_FRIEND_AGREE_ALL", Value=21)]
      STC_FRIEND_AGREE_ALL = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_FRIEND_REFUSE_ALL", Value=22)]
      CTS_FRIEND_REFUSE_ALL = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_FRIEND_REFUSE_ALL", Value=23)]
      STC_FRIEND_REFUSE_ALL = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_FRIEND_SEARCH", Value=24)]
      CTS_FRIEND_SEARCH = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_FRIEND_SEARCH", Value=25)]
      STC_FRIEND_SEARCH = 25
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"NOTIFY_TYPE")]
    public enum NOTIFY_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRIEND_APPLY", Value=0)]
      FRIEND_APPLY = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADD_FRIEND", Value=1)]
      ADD_FRIEND = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DELETE_FRIEND", Value=2)]
      DELETE_FRIEND = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLACK_FRIEND", Value=3)]
      BLACK_FRIEND = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRIEND_ONLINE", Value=4)]
      FRIEND_ONLINE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRIEND_OFFLINE", Value=5)]
      FRIEND_OFFLINE = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RESULT_TYPE")]
    public enum RESULT_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=2)]
      FAIL = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RELATION_TYPE")]
    public enum RELATION_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMMON", Value=0)]
      COMMON = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MASK", Value=1)]
      MASK = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLACKLIST", Value=2)]
      BLACKLIST = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRIEND", Value=3)]
      FRIEND = 3
    }
  
}