//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/Role_Msg.proto
namespace MANGO_ROLE_MSG
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_LOGIN_MSG")]
  public partial class CTS_LOGIN_MSG : global::ProtoBuf.IExtensible
  {
    public CTS_LOGIN_MSG() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }

    private uint _characteristic = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"characteristic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint characteristic
    {
      get { return _characteristic; }
      set { _characteristic = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_LOGIN_MSG")]
  public partial class STC_LOGIN_MSG : global::ProtoBuf.IExtensible
  {
    public STC_LOGIN_MSG() {}
    
    private MANGO_ROLE_MSG.LOGIN_STATE _state;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MANGO_ROLE_MSG.LOGIN_STATE state
    {
      get { return _state; }
      set { _state = value; }
    }

    private string _info = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string info
    {
      get { return _info; }
      set { _info = value; }
    }

    private uint _userId = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }

    private uint _exp = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }

    private uint _gold = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }

    private uint _diamond = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }

    private uint _characteristic = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"characteristic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint characteristic
    {
      get { return _characteristic; }
      set { _characteristic = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MSG_TYPE")]
    public enum MSG_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_TYPE_ROLE", Value=1)]
      MSG_TYPE_ROLE = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MSG_ID")]
    public enum MSG_ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_LOGIN", Value=1)]
      CTS_LOGIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_LOGIN", Value=2)]
      STC_LOGIN = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LOGIN_STATE")]
    public enum LOGIN_STATE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_ROLE", Value=2)]
      NO_ROLE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAILURE", Value=3)]
      FAILURE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_CREATE", Value=4)]
      ERROR_CREATE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_SUCCESS", Value=5)]
      CREATE_SUCCESS = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DISABLE", Value=6)]
      DISABLE = 6
    }
  
}