//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/Room_Msg.proto
namespace MANGO_ROOM_MSG
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PLAYER_INFO")]
  public partial class PLAYER_INFO : global::ProtoBuf.IExtensible
  {
    public PLAYER_INFO() {}
    
    private uint _PLAYER_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PLAYER_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PLAYER_ID
    {
      get { return _PLAYER_ID; }
      set { _PLAYER_ID = value; }
    }

    private string _PLAYER_NAME = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"PLAYER_NAME", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PLAYER_NAME
    {
      get { return _PLAYER_NAME; }
      set { _PLAYER_NAME = value; }
    }
    private uint _Characteristic;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Characteristic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Characteristic
    {
      get { return _Characteristic; }
      set { _Characteristic = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PLAYER_CHANGE")]
  public partial class PLAYER_CHANGE : global::ProtoBuf.IExtensible
  {
    public PLAYER_CHANGE() {}
    
    private MANGO_ROOM_MSG.PLAYER_INFO _PLAYER;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PLAYER", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MANGO_ROOM_MSG.PLAYER_INFO PLAYER
    {
      get { return _PLAYER; }
      set { _PLAYER = value; }
    }
    private MANGO_ROOM_MSG.ROOM_PLAYERCHANGE_STATE _STATE;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"STATE", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MANGO_ROOM_MSG.ROOM_PLAYERCHANGE_STATE STATE
    {
      get { return _STATE; }
      set { _STATE = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_JOIN_ROOM")]
  public partial class CTS_JOIN_ROOM : global::ProtoBuf.IExtensible
  {
    public CTS_JOIN_ROOM() {}
    
    private uint _ROOM_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ROOM_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ROOM_ID
    {
      get { return _ROOM_ID; }
      set { _ROOM_ID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_LEAVE_ROOM")]
  public partial class CTS_LEAVE_ROOM : global::ProtoBuf.IExtensible
  {
    public CTS_LEAVE_ROOM() {}
    
    private uint _ROOM_ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ROOM_ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ROOM_ID
    {
      get { return _ROOM_ID; }
      set { _ROOM_ID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_JOIN_ROOM")]
  public partial class STC_JOIN_ROOM : global::ProtoBuf.IExtensible
  {
    public STC_JOIN_ROOM() {}
    
    private MANGO_ROOM_MSG.JOIN_RESULT _RESULT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RESULT", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MANGO_ROOM_MSG.JOIN_RESULT RESULT
    {
      get { return _RESULT; }
      set { _RESULT = value; }
    }

    private string _INFO = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"INFO", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string INFO
    {
      get { return _INFO; }
      set { _INFO = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_PLAYER_CHANGE_NOTIFY")]
  public partial class STC_PLAYER_CHANGE_NOTIFY : global::ProtoBuf.IExtensible
  {
    public STC_PLAYER_CHANGE_NOTIFY() {}
    
    private readonly global::System.Collections.Generic.List<MANGO_ROOM_MSG.PLAYER_CHANGE> _LIST_PLAYER_CHANGE = new global::System.Collections.Generic.List<MANGO_ROOM_MSG.PLAYER_CHANGE>();
    [global::ProtoBuf.ProtoMember(1, Name=@"LIST_PLAYER_CHANGE", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MANGO_ROOM_MSG.PLAYER_CHANGE> LIST_PLAYER_CHANGE
    {
      get { return _LIST_PLAYER_CHANGE; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MSG_TYPE")]
    public enum MSG_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_TYPE_ROOM", Value=2)]
      MSG_TYPE_ROOM = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MSG_ID")]
    public enum MSG_ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_PLAYER_CHANGE", Value=1)]
      STC_PLAYER_CHANGE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CTS_JOIN", Value=2)]
      CTS_JOIN = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STC_JOIN", Value=3)]
      STC_JOIN = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"JOIN_RESULT")]
    public enum JOIN_RESULT
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAILED", Value=2)]
      FAILED = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ROOM_PLAYERCHANGE_STATE")]
    public enum ROOM_PLAYERCHANGE_STATE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"JOIN", Value=1)]
      JOIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEAVE", Value=2)]
      LEAVE = 2
    }
  
}