// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/msg_11_storage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace STORAGEMSG {

  /// <summary>Holder for reflection information generated from protos/msg_11_storage.proto</summary>
  public static partial class Msg11StorageReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/msg_11_storage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Msg11StorageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chtwcm90b3MvbXNnXzExX3N0b3JhZ2UucHJvdG8SC1NUT1JBR0VfTVNHIjAK",
            "E0NUU19TRVRfU1RPUkFHRV9NU0cSCwoDS0VZGAEgAigJEgwKBERBVEEYAiAB",
            "KAwiIgoTQ1RTX0dFVF9TVE9SQUdFX01TRxILCgNLRVkYASACKAkiagoTU1RD",
            "X0dFVF9TVE9SQUdFX01TRxIqCgZSRVNVTFQYASACKA4yGi5TVE9SQUdFX01T",
            "Ry5BQ1RJT05fUkVTVUxUEgwKBElORk8YAiABKAkSCwoDS0VZGAMgASgJEgwK",
            "BERBVEEYBCABKAwiNAoSQ1RTX0dFVF9HTE9CQUxfTVNHEhEKCVBMQVlFUl9J",
            "RBgBIAIoDRILCgNLRVkYAiACKAkifAoSU1RDX0dFVF9HTE9CQUxfTVNHEioK",
            "BlJFU1VMVBgBIAIoDjIaLlNUT1JBR0VfTVNHLkFDVElPTl9SRVNVTFQSDAoE",
            "SU5GTxgCIAEoCRILCgNLRVkYAyABKAkSDAoEREFUQRgEIAEoDBIRCglQTEFZ",
            "RVJfSUQYBSABKA0iNgoOUGxheWVyQ29pbkRhdGESEAoIZ29sZENvaW4YASAC",
            "KA0SEgoKY3JlZGl0Q29pbhgCIAIoDSogCghDTURfVFlQRRIUChBNU0dfVFlQ",
            "RV9TVE9SQUdFEAsqbwoGQ01EX0lEEhMKD0NUU19TRVRfU1RPUkFHRRABEhMK",
            "D0NUU19HRVRfU1RPUkFHRRACEhMKD1NUQ19HRVRfU1RPUkFHRRADEhIKDkNU",
            "U19HRVRfR0xPQkFMEAQSEgoOU1RDX0dFVF9HTE9CQUwQBSooCg1BQ1RJT05f",
            "UkVTVUxUEgsKB1NVQ0NFU1MQARIKCgZGQUlMRUQQAkIoChdjbi5lZGVuLmdh",
            "dGV3YXkubWVzc2FnZUILU1RPUkFHRV9NU0dIAw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::STORAGEMSG.CMD_TYPE), typeof(global::STORAGEMSG.CMD_ID), typeof(global::STORAGEMSG.ACTION_RESULT), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::STORAGEMSG.CTS_SET_STORAGE_MSG), global::STORAGEMSG.CTS_SET_STORAGE_MSG.Parser, new[]{ "KEY", "DATA" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::STORAGEMSG.CTS_GET_STORAGE_MSG), global::STORAGEMSG.CTS_GET_STORAGE_MSG.Parser, new[]{ "KEY" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::STORAGEMSG.STC_GET_STORAGE_MSG), global::STORAGEMSG.STC_GET_STORAGE_MSG.Parser, new[]{ "RESULT", "INFO", "KEY", "DATA" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::STORAGEMSG.CTS_GET_GLOBAL_MSG), global::STORAGEMSG.CTS_GET_GLOBAL_MSG.Parser, new[]{ "PLAYERID", "KEY" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::STORAGEMSG.STC_GET_GLOBAL_MSG), global::STORAGEMSG.STC_GET_GLOBAL_MSG.Parser, new[]{ "RESULT", "INFO", "KEY", "DATA", "PLAYERID" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::STORAGEMSG.PlayerCoinData), global::STORAGEMSG.PlayerCoinData.Parser, new[]{ "GoldCoin", "CreditCoin" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum CMD_TYPE {
    [pbr::OriginalName("MSG_TYPE_STORAGE")] MsgTypeStorage = 11,
  }

  public enum CMD_ID {
    [pbr::OriginalName("CTS_SET_STORAGE")] CtsSetStorage = 1,
    [pbr::OriginalName("CTS_GET_STORAGE")] CtsGetStorage = 2,
    [pbr::OriginalName("STC_GET_STORAGE")] StcGetStorage = 3,
    [pbr::OriginalName("CTS_GET_GLOBAL")] CtsGetGlobal = 4,
    [pbr::OriginalName("STC_GET_GLOBAL")] StcGetGlobal = 5,
  }

  public enum ACTION_RESULT {
    [pbr::OriginalName("SUCCESS")] Success = 1,
    [pbr::OriginalName("FAILED")] Failed = 2,
  }

  #endregion

  #region Messages
  public sealed partial class CTS_SET_STORAGE_MSG : pb::IMessage<CTS_SET_STORAGE_MSG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CTS_SET_STORAGE_MSG> _parser = new pb::MessageParser<CTS_SET_STORAGE_MSG>(() => new CTS_SET_STORAGE_MSG());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CTS_SET_STORAGE_MSG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::STORAGEMSG.Msg11StorageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_SET_STORAGE_MSG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_SET_STORAGE_MSG(CTS_SET_STORAGE_MSG other) : this() {
      kEY_ = other.kEY_;
      dATA_ = other.dATA_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_SET_STORAGE_MSG Clone() {
      return new CTS_SET_STORAGE_MSG(this);
    }

    /// <summary>Field number for the "KEY" field.</summary>
    public const int KEYFieldNumber = 1;
    private readonly static string KEYDefaultValue = "";

    private string kEY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string KEY {
      get { return kEY_ ?? KEYDefaultValue; }
      set {
        kEY_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "KEY" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasKEY {
      get { return kEY_ != null; }
    }
    /// <summary>Clears the value of the "KEY" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearKEY() {
      kEY_ = null;
    }

    /// <summary>Field number for the "DATA" field.</summary>
    public const int DATAFieldNumber = 2;
    private readonly static pb::ByteString DATADefaultValue = pb::ByteString.Empty;

    private pb::ByteString dATA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString DATA {
      get { return dATA_ ?? DATADefaultValue; }
      set {
        dATA_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "DATA" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDATA {
      get { return dATA_ != null; }
    }
    /// <summary>Clears the value of the "DATA" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDATA() {
      dATA_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CTS_SET_STORAGE_MSG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CTS_SET_STORAGE_MSG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (KEY != other.KEY) return false;
      if (DATA != other.DATA) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasKEY) hash ^= KEY.GetHashCode();
      if (HasDATA) hash ^= DATA.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasKEY) {
        output.WriteRawTag(10);
        output.WriteString(KEY);
      }
      if (HasDATA) {
        output.WriteRawTag(18);
        output.WriteBytes(DATA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasKEY) {
        output.WriteRawTag(10);
        output.WriteString(KEY);
      }
      if (HasDATA) {
        output.WriteRawTag(18);
        output.WriteBytes(DATA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasKEY) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(KEY);
      }
      if (HasDATA) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(DATA);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CTS_SET_STORAGE_MSG other) {
      if (other == null) {
        return;
      }
      if (other.HasKEY) {
        KEY = other.KEY;
      }
      if (other.HasDATA) {
        DATA = other.DATA;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            KEY = input.ReadString();
            break;
          }
          case 18: {
            DATA = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            KEY = input.ReadString();
            break;
          }
          case 18: {
            DATA = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CTS_GET_STORAGE_MSG : pb::IMessage<CTS_GET_STORAGE_MSG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CTS_GET_STORAGE_MSG> _parser = new pb::MessageParser<CTS_GET_STORAGE_MSG>(() => new CTS_GET_STORAGE_MSG());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CTS_GET_STORAGE_MSG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::STORAGEMSG.Msg11StorageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_GET_STORAGE_MSG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_GET_STORAGE_MSG(CTS_GET_STORAGE_MSG other) : this() {
      kEY_ = other.kEY_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_GET_STORAGE_MSG Clone() {
      return new CTS_GET_STORAGE_MSG(this);
    }

    /// <summary>Field number for the "KEY" field.</summary>
    public const int KEYFieldNumber = 1;
    private readonly static string KEYDefaultValue = "";

    private string kEY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string KEY {
      get { return kEY_ ?? KEYDefaultValue; }
      set {
        kEY_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "KEY" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasKEY {
      get { return kEY_ != null; }
    }
    /// <summary>Clears the value of the "KEY" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearKEY() {
      kEY_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CTS_GET_STORAGE_MSG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CTS_GET_STORAGE_MSG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (KEY != other.KEY) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasKEY) hash ^= KEY.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasKEY) {
        output.WriteRawTag(10);
        output.WriteString(KEY);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasKEY) {
        output.WriteRawTag(10);
        output.WriteString(KEY);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasKEY) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(KEY);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CTS_GET_STORAGE_MSG other) {
      if (other == null) {
        return;
      }
      if (other.HasKEY) {
        KEY = other.KEY;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            KEY = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            KEY = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class STC_GET_STORAGE_MSG : pb::IMessage<STC_GET_STORAGE_MSG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<STC_GET_STORAGE_MSG> _parser = new pb::MessageParser<STC_GET_STORAGE_MSG>(() => new STC_GET_STORAGE_MSG());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<STC_GET_STORAGE_MSG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::STORAGEMSG.Msg11StorageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_GET_STORAGE_MSG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_GET_STORAGE_MSG(STC_GET_STORAGE_MSG other) : this() {
      _hasBits0 = other._hasBits0;
      rESULT_ = other.rESULT_;
      iNFO_ = other.iNFO_;
      kEY_ = other.kEY_;
      dATA_ = other.dATA_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_GET_STORAGE_MSG Clone() {
      return new STC_GET_STORAGE_MSG(this);
    }

    /// <summary>Field number for the "RESULT" field.</summary>
    public const int RESULTFieldNumber = 1;
    private readonly static global::STORAGEMSG.ACTION_RESULT RESULTDefaultValue = global::STORAGEMSG.ACTION_RESULT.Success;

    private global::STORAGEMSG.ACTION_RESULT rESULT_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STORAGEMSG.ACTION_RESULT RESULT {
      get { if ((_hasBits0 & 1) != 0) { return rESULT_; } else { return RESULTDefaultValue; } }
      set {
        _hasBits0 |= 1;
        rESULT_ = value;
      }
    }
    /// <summary>Gets whether the "RESULT" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRESULT {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "RESULT" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRESULT() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "INFO" field.</summary>
    public const int INFOFieldNumber = 2;
    private readonly static string INFODefaultValue = "";

    private string iNFO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string INFO {
      get { return iNFO_ ?? INFODefaultValue; }
      set {
        iNFO_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "INFO" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasINFO {
      get { return iNFO_ != null; }
    }
    /// <summary>Clears the value of the "INFO" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearINFO() {
      iNFO_ = null;
    }

    /// <summary>Field number for the "KEY" field.</summary>
    public const int KEYFieldNumber = 3;
    private readonly static string KEYDefaultValue = "";

    private string kEY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string KEY {
      get { return kEY_ ?? KEYDefaultValue; }
      set {
        kEY_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "KEY" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasKEY {
      get { return kEY_ != null; }
    }
    /// <summary>Clears the value of the "KEY" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearKEY() {
      kEY_ = null;
    }

    /// <summary>Field number for the "DATA" field.</summary>
    public const int DATAFieldNumber = 4;
    private readonly static pb::ByteString DATADefaultValue = pb::ByteString.Empty;

    private pb::ByteString dATA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString DATA {
      get { return dATA_ ?? DATADefaultValue; }
      set {
        dATA_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "DATA" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDATA {
      get { return dATA_ != null; }
    }
    /// <summary>Clears the value of the "DATA" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDATA() {
      dATA_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as STC_GET_STORAGE_MSG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(STC_GET_STORAGE_MSG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RESULT != other.RESULT) return false;
      if (INFO != other.INFO) return false;
      if (KEY != other.KEY) return false;
      if (DATA != other.DATA) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasRESULT) hash ^= RESULT.GetHashCode();
      if (HasINFO) hash ^= INFO.GetHashCode();
      if (HasKEY) hash ^= KEY.GetHashCode();
      if (HasDATA) hash ^= DATA.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasRESULT) {
        output.WriteRawTag(8);
        output.WriteEnum((int) RESULT);
      }
      if (HasINFO) {
        output.WriteRawTag(18);
        output.WriteString(INFO);
      }
      if (HasKEY) {
        output.WriteRawTag(26);
        output.WriteString(KEY);
      }
      if (HasDATA) {
        output.WriteRawTag(34);
        output.WriteBytes(DATA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasRESULT) {
        output.WriteRawTag(8);
        output.WriteEnum((int) RESULT);
      }
      if (HasINFO) {
        output.WriteRawTag(18);
        output.WriteString(INFO);
      }
      if (HasKEY) {
        output.WriteRawTag(26);
        output.WriteString(KEY);
      }
      if (HasDATA) {
        output.WriteRawTag(34);
        output.WriteBytes(DATA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasRESULT) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RESULT);
      }
      if (HasINFO) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(INFO);
      }
      if (HasKEY) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(KEY);
      }
      if (HasDATA) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(DATA);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(STC_GET_STORAGE_MSG other) {
      if (other == null) {
        return;
      }
      if (other.HasRESULT) {
        RESULT = other.RESULT;
      }
      if (other.HasINFO) {
        INFO = other.INFO;
      }
      if (other.HasKEY) {
        KEY = other.KEY;
      }
      if (other.HasDATA) {
        DATA = other.DATA;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RESULT = (global::STORAGEMSG.ACTION_RESULT) input.ReadEnum();
            break;
          }
          case 18: {
            INFO = input.ReadString();
            break;
          }
          case 26: {
            KEY = input.ReadString();
            break;
          }
          case 34: {
            DATA = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RESULT = (global::STORAGEMSG.ACTION_RESULT) input.ReadEnum();
            break;
          }
          case 18: {
            INFO = input.ReadString();
            break;
          }
          case 26: {
            KEY = input.ReadString();
            break;
          }
          case 34: {
            DATA = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CTS_GET_GLOBAL_MSG : pb::IMessage<CTS_GET_GLOBAL_MSG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CTS_GET_GLOBAL_MSG> _parser = new pb::MessageParser<CTS_GET_GLOBAL_MSG>(() => new CTS_GET_GLOBAL_MSG());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CTS_GET_GLOBAL_MSG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::STORAGEMSG.Msg11StorageReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_GET_GLOBAL_MSG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_GET_GLOBAL_MSG(CTS_GET_GLOBAL_MSG other) : this() {
      _hasBits0 = other._hasBits0;
      pLAYERID_ = other.pLAYERID_;
      kEY_ = other.kEY_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_GET_GLOBAL_MSG Clone() {
      return new CTS_GET_GLOBAL_MSG(this);
    }

    /// <summary>Field number for the "PLAYER_ID" field.</summary>
    public const int PLAYERIDFieldNumber = 1;
    private readonly static uint PLAYERIDDefaultValue = 0;

    private uint pLAYERID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PLAYERID {
      get { if ((_hasBits0 & 1) != 0) { return pLAYERID_; } else { return PLAYERIDDefaultValue; } }
      set {
        _hasBits0 |= 1;
        pLAYERID_ = value;
      }
    }
    /// <summary>Gets whether the "PLAYER_ID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPLAYERID {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "PLAYER_ID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPLAYERID() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "KEY" field.</summary>
    public const int KEYFieldNumber = 2;
    private readonly static string KEYDefaultValue = "";

    private string kEY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string KEY {
      get { return kEY_ ?? KEYDefaultValue; }
      set {
        kEY_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "KEY" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasKEY {
      get { return kEY_ != null; }
    }
    /// <summary>Clears the value of the "KEY" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearKEY() {
      kEY_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CTS_GET_GLOBAL_MSG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CTS_GET_GLOBAL_MSG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PLAYERID != other.PLAYERID) return false;
      if (KEY != other.KEY) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPLAYERID) hash ^= PLAYERID.GetHashCode();
      if (HasKEY) hash ^= KEY.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPLAYERID) {
        output.WriteRawTag(8);
        output.WriteUInt32(PLAYERID);
      }
      if (HasKEY) {
        output.WriteRawTag(18);
        output.WriteString(KEY);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPLAYERID) {
        output.WriteRawTag(8);
        output.WriteUInt32(PLAYERID);
      }
      if (HasKEY) {
        output.WriteRawTag(18);
        output.WriteString(KEY);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasPLAYERID) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PLAYERID);
      }
      if (HasKEY) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(KEY);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CTS_GET_GLOBAL_MSG other) {
      if (other == null) {
        return;
      }
      if (other.HasPLAYERID) {
        PLAYERID = other.PLAYERID;
      }
      if (other.HasKEY) {
        KEY = other.KEY;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PLAYERID = input.ReadUInt32();
            break;
          }
          case 18: {
            KEY = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PLAYERID = input.ReadUInt32();
            break;
          }
          case 18: {
            KEY = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class STC_GET_GLOBAL_MSG : pb::IMessage<STC_GET_GLOBAL_MSG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<STC_GET_GLOBAL_MSG> _parser = new pb::MessageParser<STC_GET_GLOBAL_MSG>(() => new STC_GET_GLOBAL_MSG());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<STC_GET_GLOBAL_MSG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::STORAGEMSG.Msg11StorageReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_GET_GLOBAL_MSG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_GET_GLOBAL_MSG(STC_GET_GLOBAL_MSG other) : this() {
      _hasBits0 = other._hasBits0;
      rESULT_ = other.rESULT_;
      iNFO_ = other.iNFO_;
      kEY_ = other.kEY_;
      dATA_ = other.dATA_;
      pLAYERID_ = other.pLAYERID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_GET_GLOBAL_MSG Clone() {
      return new STC_GET_GLOBAL_MSG(this);
    }

    /// <summary>Field number for the "RESULT" field.</summary>
    public const int RESULTFieldNumber = 1;
    private readonly static global::STORAGEMSG.ACTION_RESULT RESULTDefaultValue = global::STORAGEMSG.ACTION_RESULT.Success;

    private global::STORAGEMSG.ACTION_RESULT rESULT_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STORAGEMSG.ACTION_RESULT RESULT {
      get { if ((_hasBits0 & 1) != 0) { return rESULT_; } else { return RESULTDefaultValue; } }
      set {
        _hasBits0 |= 1;
        rESULT_ = value;
      }
    }
    /// <summary>Gets whether the "RESULT" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRESULT {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "RESULT" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRESULT() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "INFO" field.</summary>
    public const int INFOFieldNumber = 2;
    private readonly static string INFODefaultValue = "";

    private string iNFO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string INFO {
      get { return iNFO_ ?? INFODefaultValue; }
      set {
        iNFO_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "INFO" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasINFO {
      get { return iNFO_ != null; }
    }
    /// <summary>Clears the value of the "INFO" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearINFO() {
      iNFO_ = null;
    }

    /// <summary>Field number for the "KEY" field.</summary>
    public const int KEYFieldNumber = 3;
    private readonly static string KEYDefaultValue = "";

    private string kEY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string KEY {
      get { return kEY_ ?? KEYDefaultValue; }
      set {
        kEY_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "KEY" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasKEY {
      get { return kEY_ != null; }
    }
    /// <summary>Clears the value of the "KEY" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearKEY() {
      kEY_ = null;
    }

    /// <summary>Field number for the "DATA" field.</summary>
    public const int DATAFieldNumber = 4;
    private readonly static pb::ByteString DATADefaultValue = pb::ByteString.Empty;

    private pb::ByteString dATA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString DATA {
      get { return dATA_ ?? DATADefaultValue; }
      set {
        dATA_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "DATA" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDATA {
      get { return dATA_ != null; }
    }
    /// <summary>Clears the value of the "DATA" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDATA() {
      dATA_ = null;
    }

    /// <summary>Field number for the "PLAYER_ID" field.</summary>
    public const int PLAYERIDFieldNumber = 5;
    private readonly static uint PLAYERIDDefaultValue = 0;

    private uint pLAYERID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PLAYERID {
      get { if ((_hasBits0 & 2) != 0) { return pLAYERID_; } else { return PLAYERIDDefaultValue; } }
      set {
        _hasBits0 |= 2;
        pLAYERID_ = value;
      }
    }
    /// <summary>Gets whether the "PLAYER_ID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPLAYERID {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "PLAYER_ID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPLAYERID() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as STC_GET_GLOBAL_MSG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(STC_GET_GLOBAL_MSG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RESULT != other.RESULT) return false;
      if (INFO != other.INFO) return false;
      if (KEY != other.KEY) return false;
      if (DATA != other.DATA) return false;
      if (PLAYERID != other.PLAYERID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasRESULT) hash ^= RESULT.GetHashCode();
      if (HasINFO) hash ^= INFO.GetHashCode();
      if (HasKEY) hash ^= KEY.GetHashCode();
      if (HasDATA) hash ^= DATA.GetHashCode();
      if (HasPLAYERID) hash ^= PLAYERID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasRESULT) {
        output.WriteRawTag(8);
        output.WriteEnum((int) RESULT);
      }
      if (HasINFO) {
        output.WriteRawTag(18);
        output.WriteString(INFO);
      }
      if (HasKEY) {
        output.WriteRawTag(26);
        output.WriteString(KEY);
      }
      if (HasDATA) {
        output.WriteRawTag(34);
        output.WriteBytes(DATA);
      }
      if (HasPLAYERID) {
        output.WriteRawTag(40);
        output.WriteUInt32(PLAYERID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasRESULT) {
        output.WriteRawTag(8);
        output.WriteEnum((int) RESULT);
      }
      if (HasINFO) {
        output.WriteRawTag(18);
        output.WriteString(INFO);
      }
      if (HasKEY) {
        output.WriteRawTag(26);
        output.WriteString(KEY);
      }
      if (HasDATA) {
        output.WriteRawTag(34);
        output.WriteBytes(DATA);
      }
      if (HasPLAYERID) {
        output.WriteRawTag(40);
        output.WriteUInt32(PLAYERID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasRESULT) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RESULT);
      }
      if (HasINFO) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(INFO);
      }
      if (HasKEY) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(KEY);
      }
      if (HasDATA) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(DATA);
      }
      if (HasPLAYERID) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PLAYERID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(STC_GET_GLOBAL_MSG other) {
      if (other == null) {
        return;
      }
      if (other.HasRESULT) {
        RESULT = other.RESULT;
      }
      if (other.HasINFO) {
        INFO = other.INFO;
      }
      if (other.HasKEY) {
        KEY = other.KEY;
      }
      if (other.HasDATA) {
        DATA = other.DATA;
      }
      if (other.HasPLAYERID) {
        PLAYERID = other.PLAYERID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RESULT = (global::STORAGEMSG.ACTION_RESULT) input.ReadEnum();
            break;
          }
          case 18: {
            INFO = input.ReadString();
            break;
          }
          case 26: {
            KEY = input.ReadString();
            break;
          }
          case 34: {
            DATA = input.ReadBytes();
            break;
          }
          case 40: {
            PLAYERID = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RESULT = (global::STORAGEMSG.ACTION_RESULT) input.ReadEnum();
            break;
          }
          case 18: {
            INFO = input.ReadString();
            break;
          }
          case 26: {
            KEY = input.ReadString();
            break;
          }
          case 34: {
            DATA = input.ReadBytes();
            break;
          }
          case 40: {
            PLAYERID = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///玩家金币属性
  /// </summary>
  public sealed partial class PlayerCoinData : pb::IMessage<PlayerCoinData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerCoinData> _parser = new pb::MessageParser<PlayerCoinData>(() => new PlayerCoinData());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerCoinData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::STORAGEMSG.Msg11StorageReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerCoinData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerCoinData(PlayerCoinData other) : this() {
      _hasBits0 = other._hasBits0;
      goldCoin_ = other.goldCoin_;
      creditCoin_ = other.creditCoin_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerCoinData Clone() {
      return new PlayerCoinData(this);
    }

    /// <summary>Field number for the "goldCoin" field.</summary>
    public const int GoldCoinFieldNumber = 1;
    private readonly static uint GoldCoinDefaultValue = 0;

    private uint goldCoin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GoldCoin {
      get { if ((_hasBits0 & 1) != 0) { return goldCoin_; } else { return GoldCoinDefaultValue; } }
      set {
        _hasBits0 |= 1;
        goldCoin_ = value;
      }
    }
    /// <summary>Gets whether the "goldCoin" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasGoldCoin {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "goldCoin" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearGoldCoin() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "creditCoin" field.</summary>
    public const int CreditCoinFieldNumber = 2;
    private readonly static uint CreditCoinDefaultValue = 0;

    private uint creditCoin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CreditCoin {
      get { if ((_hasBits0 & 2) != 0) { return creditCoin_; } else { return CreditCoinDefaultValue; } }
      set {
        _hasBits0 |= 2;
        creditCoin_ = value;
      }
    }
    /// <summary>Gets whether the "creditCoin" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCreditCoin {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "creditCoin" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCreditCoin() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerCoinData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerCoinData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GoldCoin != other.GoldCoin) return false;
      if (CreditCoin != other.CreditCoin) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasGoldCoin) hash ^= GoldCoin.GetHashCode();
      if (HasCreditCoin) hash ^= CreditCoin.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasGoldCoin) {
        output.WriteRawTag(8);
        output.WriteUInt32(GoldCoin);
      }
      if (HasCreditCoin) {
        output.WriteRawTag(16);
        output.WriteUInt32(CreditCoin);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasGoldCoin) {
        output.WriteRawTag(8);
        output.WriteUInt32(GoldCoin);
      }
      if (HasCreditCoin) {
        output.WriteRawTag(16);
        output.WriteUInt32(CreditCoin);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasGoldCoin) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GoldCoin);
      }
      if (HasCreditCoin) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CreditCoin);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerCoinData other) {
      if (other == null) {
        return;
      }
      if (other.HasGoldCoin) {
        GoldCoin = other.GoldCoin;
      }
      if (other.HasCreditCoin) {
        CreditCoin = other.CreditCoin;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GoldCoin = input.ReadUInt32();
            break;
          }
          case 16: {
            CreditCoin = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            GoldCoin = input.ReadUInt32();
            break;
          }
          case 16: {
            CreditCoin = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
