// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/msg_12_theater.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace THRATERMSG {

  /// <summary>Holder for reflection information generated from protos/msg_12_theater.proto</summary>
  public static partial class Msg12TheaterReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/msg_12_theater.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Msg12TheaterReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chtwcm90b3MvbXNnXzEyX3RoZWF0ZXIucHJvdG8SC1RIUkFURVJfTVNHKiAK",
            "CENNRF9UWVBFEhQKEE1TR19UWVBFX1RIUkFURVIQDEIoChdjbi5lZGVuLmdh",
            "dGV3YXkubWVzc2FnZUILVEhSQVRFUl9NU0dIAw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::THRATERMSG.CMD_TYPE), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CMD_TYPE {
    [pbr::OriginalName("MSG_TYPE_THRATER")] MsgTypeThrater = 12,
  }

  #endregion

}

#endregion Designer generated code
