// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/Room_Msg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MANGOROOMMSG {

  /// <summary>Holder for reflection information generated from protos/Room_Msg.proto</summary>
  public static partial class RoomMsgReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/Room_Msg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RoomMsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVwcm90b3MvUm9vbV9Nc2cucHJvdG8SDk1BTkdPX1JPT01fTVNHIioKB1ZF",
            "Q1RPUjMSCQoBWBgBIAIoAhIJCgFZGAIgAigCEgkKAVoYAyACKAIiTQoLUExB",
            "WUVSX0lORk8SEQoJUExBWUVSX0lEGAEgAigNEhMKC1BMQVlFUl9OQU1FGAIg",
            "ASgJEhYKDkNoYXJhY3RlcmlzdGljGAMgAigNInQKDVBMQVlFUl9DSEFOR0US",
            "KwoGUExBWUVSGAEgAigLMhsuTUFOR09fUk9PTV9NU0cuUExBWUVSX0lORk8S",
            "NgoFU1RBVEUYAiACKA4yJy5NQU5HT19ST09NX01TRy5ST09NX1BMQVlFUkNI",
            "QU5HRV9TVEFURSIgCg1DVFNfSk9JTl9ST09NEg8KB1JPT01fSUQYASACKA0i",
            "IQoOQ1RTX0xFQVZFX1JPT00SDwoHUk9PTV9JRBgBIAIoDSJKCg1TVENfSk9J",
            "Tl9ST09NEisKBlJFU1VMVBgBIAIoDjIbLk1BTkdPX1JPT01fTVNHLkpPSU5f",
            "UkVTVUxUEgwKBElORk8YAiABKAkiVQoYU1RDX1BMQVlFUl9DSEFOR0VfTk9U",
            "SUZZEjkKEkxJU1RfUExBWUVSX0NIQU5HRRgBIAMoCzIdLk1BTkdPX1JPT01f",
            "TVNHLlBMQVlFUl9DSEFOR0UqHQoITVNHX1RZUEUSEQoNTVNHX1RZUEVfUk9P",
            "TRACKkoKBk1TR19JRBIVChFTVENfUExBWUVSX0NIQU5HRRABEgwKCENUU19K",
            "T0lOEAISDAoIU1RDX0pPSU4QAxINCglDVFNfTEVBVkUQBComCgtKT0lOX1JF",
            "U1VMVBILCgdTVUNDRVNTEAESCgoGRkFJTEVEEAIqLgoXUk9PTV9QTEFZRVJD",
            "SEFOR0VfU1RBVEUSCAoESk9JThABEgkKBUxFQVZFEAJCJwoYY29tLm91cnBh",
            "bG0udGFuay5tZXNzYWdlQglNQU5HT19NU0dIAw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MANGOROOMMSG.MSG_TYPE), typeof(global::MANGOROOMMSG.MSG_ID), typeof(global::MANGOROOMMSG.JOIN_RESULT), typeof(global::MANGOROOMMSG.ROOM_PLAYERCHANGE_STATE), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MANGOROOMMSG.VECTOR3), global::MANGOROOMMSG.VECTOR3.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MANGOROOMMSG.PLAYER_INFO), global::MANGOROOMMSG.PLAYER_INFO.Parser, new[]{ "PLAYERID", "PLAYERNAME", "Characteristic" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MANGOROOMMSG.PLAYER_CHANGE), global::MANGOROOMMSG.PLAYER_CHANGE.Parser, new[]{ "PLAYER", "STATE" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MANGOROOMMSG.CTS_JOIN_ROOM), global::MANGOROOMMSG.CTS_JOIN_ROOM.Parser, new[]{ "ROOMID" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MANGOROOMMSG.CTS_LEAVE_ROOM), global::MANGOROOMMSG.CTS_LEAVE_ROOM.Parser, new[]{ "ROOMID" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MANGOROOMMSG.STC_JOIN_ROOM), global::MANGOROOMMSG.STC_JOIN_ROOM.Parser, new[]{ "RESULT", "INFO" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MANGOROOMMSG.STC_PLAYER_CHANGE_NOTIFY), global::MANGOROOMMSG.STC_PLAYER_CHANGE_NOTIFY.Parser, new[]{ "LISTPLAYERCHANGE" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum MSG_TYPE {
    [pbr::OriginalName("MSG_TYPE_ROOM")] Room = 2,
  }

  public enum MSG_ID {
    [pbr::OriginalName("STC_PLAYER_CHANGE")] StcPlayerChange = 1,
    [pbr::OriginalName("CTS_JOIN")] CtsJoin = 2,
    [pbr::OriginalName("STC_JOIN")] StcJoin = 3,
    [pbr::OriginalName("CTS_LEAVE")] CtsLeave = 4,
  }

  public enum JOIN_RESULT {
    [pbr::OriginalName("SUCCESS")] Success = 1,
    [pbr::OriginalName("FAILED")] Failed = 2,
  }

  public enum ROOM_PLAYERCHANGE_STATE {
    /// <summary>
    ///加入
    /// </summary>
    [pbr::OriginalName("JOIN")] Join = 1,
    /// <summary>
    ///离开
    /// </summary>
    [pbr::OriginalName("LEAVE")] Leave = 2,
  }

  #endregion

  #region Messages
  public sealed partial class VECTOR3 : pb::IMessage<VECTOR3>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VECTOR3> _parser = new pb::MessageParser<VECTOR3>(() => new VECTOR3());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VECTOR3> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MANGOROOMMSG.RoomMsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VECTOR3() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VECTOR3(VECTOR3 other) : this() {
      _hasBits0 = other._hasBits0;
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VECTOR3 Clone() {
      return new VECTOR3(this);
    }

    /// <summary>Field number for the "X" field.</summary>
    public const int XFieldNumber = 1;
    private readonly static float XDefaultValue = 0F;

    private float x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float X {
      get { if ((_hasBits0 & 1) != 0) { return x_; } else { return XDefaultValue; } }
      set {
        _hasBits0 |= 1;
        x_ = value;
      }
    }
    /// <summary>Gets whether the "X" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasX {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "X" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearX() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "Y" field.</summary>
    public const int YFieldNumber = 2;
    private readonly static float YDefaultValue = 0F;

    private float y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Y {
      get { if ((_hasBits0 & 2) != 0) { return y_; } else { return YDefaultValue; } }
      set {
        _hasBits0 |= 2;
        y_ = value;
      }
    }
    /// <summary>Gets whether the "Y" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasY {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "Y" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearY() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "Z" field.</summary>
    public const int ZFieldNumber = 3;
    private readonly static float ZDefaultValue = 0F;

    private float z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Z {
      get { if ((_hasBits0 & 4) != 0) { return z_; } else { return ZDefaultValue; } }
      set {
        _hasBits0 |= 4;
        z_ = value;
      }
    }
    /// <summary>Gets whether the "Z" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasZ {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "Z" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearZ() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VECTOR3);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VECTOR3 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasX) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
      if (HasY) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
      if (HasZ) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasX) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (HasY) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
      if (HasZ) {
        output.WriteRawTag(29);
        output.WriteFloat(Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasX) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (HasY) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
      if (HasZ) {
        output.WriteRawTag(29);
        output.WriteFloat(Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasX) {
        size += 1 + 4;
      }
      if (HasY) {
        size += 1 + 4;
      }
      if (HasZ) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VECTOR3 other) {
      if (other == null) {
        return;
      }
      if (other.HasX) {
        X = other.X;
      }
      if (other.HasY) {
        Y = other.Y;
      }
      if (other.HasZ) {
        Z = other.Z;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
          case 29: {
            Z = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
          case 29: {
            Z = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PLAYER_INFO : pb::IMessage<PLAYER_INFO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PLAYER_INFO> _parser = new pb::MessageParser<PLAYER_INFO>(() => new PLAYER_INFO());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PLAYER_INFO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MANGOROOMMSG.RoomMsgReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PLAYER_INFO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PLAYER_INFO(PLAYER_INFO other) : this() {
      _hasBits0 = other._hasBits0;
      pLAYERID_ = other.pLAYERID_;
      pLAYERNAME_ = other.pLAYERNAME_;
      characteristic_ = other.characteristic_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PLAYER_INFO Clone() {
      return new PLAYER_INFO(this);
    }

    /// <summary>Field number for the "PLAYER_ID" field.</summary>
    public const int PLAYERIDFieldNumber = 1;
    private readonly static uint PLAYERIDDefaultValue = 0;

    private uint pLAYERID_;
    /// <summary>
    ///玩家ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PLAYERID {
      get { if ((_hasBits0 & 1) != 0) { return pLAYERID_; } else { return PLAYERIDDefaultValue; } }
      set {
        _hasBits0 |= 1;
        pLAYERID_ = value;
      }
    }
    /// <summary>Gets whether the "PLAYER_ID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPLAYERID {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "PLAYER_ID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPLAYERID() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "PLAYER_NAME" field.</summary>
    public const int PLAYERNAMEFieldNumber = 2;
    private readonly static string PLAYERNAMEDefaultValue = "";

    private string pLAYERNAME_;
    /// <summary>
    ///玩家名
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PLAYERNAME {
      get { return pLAYERNAME_ ?? PLAYERNAMEDefaultValue; }
      set {
        pLAYERNAME_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "PLAYER_NAME" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPLAYERNAME {
      get { return pLAYERNAME_ != null; }
    }
    /// <summary>Clears the value of the "PLAYER_NAME" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPLAYERNAME() {
      pLAYERNAME_ = null;
    }

    /// <summary>Field number for the "Characteristic" field.</summary>
    public const int CharacteristicFieldNumber = 3;
    private readonly static uint CharacteristicDefaultValue = 0;

    private uint characteristic_;
    /// <summary>
    ///玩家形象类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Characteristic {
      get { if ((_hasBits0 & 2) != 0) { return characteristic_; } else { return CharacteristicDefaultValue; } }
      set {
        _hasBits0 |= 2;
        characteristic_ = value;
      }
    }
    /// <summary>Gets whether the "Characteristic" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCharacteristic {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "Characteristic" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCharacteristic() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PLAYER_INFO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PLAYER_INFO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PLAYERID != other.PLAYERID) return false;
      if (PLAYERNAME != other.PLAYERNAME) return false;
      if (Characteristic != other.Characteristic) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPLAYERID) hash ^= PLAYERID.GetHashCode();
      if (HasPLAYERNAME) hash ^= PLAYERNAME.GetHashCode();
      if (HasCharacteristic) hash ^= Characteristic.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPLAYERID) {
        output.WriteRawTag(8);
        output.WriteUInt32(PLAYERID);
      }
      if (HasPLAYERNAME) {
        output.WriteRawTag(18);
        output.WriteString(PLAYERNAME);
      }
      if (HasCharacteristic) {
        output.WriteRawTag(24);
        output.WriteUInt32(Characteristic);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPLAYERID) {
        output.WriteRawTag(8);
        output.WriteUInt32(PLAYERID);
      }
      if (HasPLAYERNAME) {
        output.WriteRawTag(18);
        output.WriteString(PLAYERNAME);
      }
      if (HasCharacteristic) {
        output.WriteRawTag(24);
        output.WriteUInt32(Characteristic);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasPLAYERID) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PLAYERID);
      }
      if (HasPLAYERNAME) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PLAYERNAME);
      }
      if (HasCharacteristic) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Characteristic);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PLAYER_INFO other) {
      if (other == null) {
        return;
      }
      if (other.HasPLAYERID) {
        PLAYERID = other.PLAYERID;
      }
      if (other.HasPLAYERNAME) {
        PLAYERNAME = other.PLAYERNAME;
      }
      if (other.HasCharacteristic) {
        Characteristic = other.Characteristic;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PLAYERID = input.ReadUInt32();
            break;
          }
          case 18: {
            PLAYERNAME = input.ReadString();
            break;
          }
          case 24: {
            Characteristic = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PLAYERID = input.ReadUInt32();
            break;
          }
          case 18: {
            PLAYERNAME = input.ReadString();
            break;
          }
          case 24: {
            Characteristic = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PLAYER_CHANGE : pb::IMessage<PLAYER_CHANGE>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PLAYER_CHANGE> _parser = new pb::MessageParser<PLAYER_CHANGE>(() => new PLAYER_CHANGE());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PLAYER_CHANGE> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MANGOROOMMSG.RoomMsgReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PLAYER_CHANGE() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PLAYER_CHANGE(PLAYER_CHANGE other) : this() {
      _hasBits0 = other._hasBits0;
      pLAYER_ = other.pLAYER_ != null ? other.pLAYER_.Clone() : null;
      sTATE_ = other.sTATE_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PLAYER_CHANGE Clone() {
      return new PLAYER_CHANGE(this);
    }

    /// <summary>Field number for the "PLAYER" field.</summary>
    public const int PLAYERFieldNumber = 1;
    private global::MANGOROOMMSG.PLAYER_INFO pLAYER_;
    /// <summary>
    ///玩家信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MANGOROOMMSG.PLAYER_INFO PLAYER {
      get { return pLAYER_; }
      set {
        pLAYER_ = value;
      }
    }

    /// <summary>Field number for the "STATE" field.</summary>
    public const int STATEFieldNumber = 2;
    private readonly static global::MANGOROOMMSG.ROOM_PLAYERCHANGE_STATE STATEDefaultValue = global::MANGOROOMMSG.ROOM_PLAYERCHANGE_STATE.Join;

    private global::MANGOROOMMSG.ROOM_PLAYERCHANGE_STATE sTATE_;
    /// <summary>
    ///加入或离开状态
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MANGOROOMMSG.ROOM_PLAYERCHANGE_STATE STATE {
      get { if ((_hasBits0 & 1) != 0) { return sTATE_; } else { return STATEDefaultValue; } }
      set {
        _hasBits0 |= 1;
        sTATE_ = value;
      }
    }
    /// <summary>Gets whether the "STATE" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSTATE {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "STATE" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSTATE() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PLAYER_CHANGE);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PLAYER_CHANGE other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PLAYER, other.PLAYER)) return false;
      if (STATE != other.STATE) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (pLAYER_ != null) hash ^= PLAYER.GetHashCode();
      if (HasSTATE) hash ^= STATE.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (pLAYER_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PLAYER);
      }
      if (HasSTATE) {
        output.WriteRawTag(16);
        output.WriteEnum((int) STATE);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (pLAYER_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PLAYER);
      }
      if (HasSTATE) {
        output.WriteRawTag(16);
        output.WriteEnum((int) STATE);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (pLAYER_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PLAYER);
      }
      if (HasSTATE) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) STATE);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PLAYER_CHANGE other) {
      if (other == null) {
        return;
      }
      if (other.pLAYER_ != null) {
        if (pLAYER_ == null) {
          PLAYER = new global::MANGOROOMMSG.PLAYER_INFO();
        }
        PLAYER.MergeFrom(other.PLAYER);
      }
      if (other.HasSTATE) {
        STATE = other.STATE;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (pLAYER_ == null) {
              PLAYER = new global::MANGOROOMMSG.PLAYER_INFO();
            }
            input.ReadMessage(PLAYER);
            break;
          }
          case 16: {
            STATE = (global::MANGOROOMMSG.ROOM_PLAYERCHANGE_STATE) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (pLAYER_ == null) {
              PLAYER = new global::MANGOROOMMSG.PLAYER_INFO();
            }
            input.ReadMessage(PLAYER);
            break;
          }
          case 16: {
            STATE = (global::MANGOROOMMSG.ROOM_PLAYERCHANGE_STATE) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CTS_JOIN_ROOM : pb::IMessage<CTS_JOIN_ROOM>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CTS_JOIN_ROOM> _parser = new pb::MessageParser<CTS_JOIN_ROOM>(() => new CTS_JOIN_ROOM());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CTS_JOIN_ROOM> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MANGOROOMMSG.RoomMsgReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_JOIN_ROOM() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_JOIN_ROOM(CTS_JOIN_ROOM other) : this() {
      _hasBits0 = other._hasBits0;
      rOOMID_ = other.rOOMID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_JOIN_ROOM Clone() {
      return new CTS_JOIN_ROOM(this);
    }

    /// <summary>Field number for the "ROOM_ID" field.</summary>
    public const int ROOMIDFieldNumber = 1;
    private readonly static uint ROOMIDDefaultValue = 0;

    private uint rOOMID_;
    /// <summary>
    /// 房间号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ROOMID {
      get { if ((_hasBits0 & 1) != 0) { return rOOMID_; } else { return ROOMIDDefaultValue; } }
      set {
        _hasBits0 |= 1;
        rOOMID_ = value;
      }
    }
    /// <summary>Gets whether the "ROOM_ID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasROOMID {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "ROOM_ID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearROOMID() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CTS_JOIN_ROOM);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CTS_JOIN_ROOM other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ROOMID != other.ROOMID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasROOMID) hash ^= ROOMID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasROOMID) {
        output.WriteRawTag(8);
        output.WriteUInt32(ROOMID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasROOMID) {
        output.WriteRawTag(8);
        output.WriteUInt32(ROOMID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasROOMID) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ROOMID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CTS_JOIN_ROOM other) {
      if (other == null) {
        return;
      }
      if (other.HasROOMID) {
        ROOMID = other.ROOMID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ROOMID = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ROOMID = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CTS_LEAVE_ROOM : pb::IMessage<CTS_LEAVE_ROOM>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CTS_LEAVE_ROOM> _parser = new pb::MessageParser<CTS_LEAVE_ROOM>(() => new CTS_LEAVE_ROOM());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CTS_LEAVE_ROOM> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MANGOROOMMSG.RoomMsgReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_LEAVE_ROOM() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_LEAVE_ROOM(CTS_LEAVE_ROOM other) : this() {
      _hasBits0 = other._hasBits0;
      rOOMID_ = other.rOOMID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_LEAVE_ROOM Clone() {
      return new CTS_LEAVE_ROOM(this);
    }

    /// <summary>Field number for the "ROOM_ID" field.</summary>
    public const int ROOMIDFieldNumber = 1;
    private readonly static uint ROOMIDDefaultValue = 0;

    private uint rOOMID_;
    /// <summary>
    /// 房间号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ROOMID {
      get { if ((_hasBits0 & 1) != 0) { return rOOMID_; } else { return ROOMIDDefaultValue; } }
      set {
        _hasBits0 |= 1;
        rOOMID_ = value;
      }
    }
    /// <summary>Gets whether the "ROOM_ID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasROOMID {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "ROOM_ID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearROOMID() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CTS_LEAVE_ROOM);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CTS_LEAVE_ROOM other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ROOMID != other.ROOMID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasROOMID) hash ^= ROOMID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasROOMID) {
        output.WriteRawTag(8);
        output.WriteUInt32(ROOMID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasROOMID) {
        output.WriteRawTag(8);
        output.WriteUInt32(ROOMID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasROOMID) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ROOMID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CTS_LEAVE_ROOM other) {
      if (other == null) {
        return;
      }
      if (other.HasROOMID) {
        ROOMID = other.ROOMID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ROOMID = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ROOMID = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class STC_JOIN_ROOM : pb::IMessage<STC_JOIN_ROOM>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<STC_JOIN_ROOM> _parser = new pb::MessageParser<STC_JOIN_ROOM>(() => new STC_JOIN_ROOM());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<STC_JOIN_ROOM> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MANGOROOMMSG.RoomMsgReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_JOIN_ROOM() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_JOIN_ROOM(STC_JOIN_ROOM other) : this() {
      _hasBits0 = other._hasBits0;
      rESULT_ = other.rESULT_;
      iNFO_ = other.iNFO_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_JOIN_ROOM Clone() {
      return new STC_JOIN_ROOM(this);
    }

    /// <summary>Field number for the "RESULT" field.</summary>
    public const int RESULTFieldNumber = 1;
    private readonly static global::MANGOROOMMSG.JOIN_RESULT RESULTDefaultValue = global::MANGOROOMMSG.JOIN_RESULT.Success;

    private global::MANGOROOMMSG.JOIN_RESULT rESULT_;
    /// <summary>
    /// 房间号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MANGOROOMMSG.JOIN_RESULT RESULT {
      get { if ((_hasBits0 & 1) != 0) { return rESULT_; } else { return RESULTDefaultValue; } }
      set {
        _hasBits0 |= 1;
        rESULT_ = value;
      }
    }
    /// <summary>Gets whether the "RESULT" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRESULT {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "RESULT" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRESULT() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "INFO" field.</summary>
    public const int INFOFieldNumber = 2;
    private readonly static string INFODefaultValue = "";

    private string iNFO_;
    /// <summary>
    ///玩家信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string INFO {
      get { return iNFO_ ?? INFODefaultValue; }
      set {
        iNFO_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "INFO" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasINFO {
      get { return iNFO_ != null; }
    }
    /// <summary>Clears the value of the "INFO" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearINFO() {
      iNFO_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as STC_JOIN_ROOM);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(STC_JOIN_ROOM other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RESULT != other.RESULT) return false;
      if (INFO != other.INFO) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasRESULT) hash ^= RESULT.GetHashCode();
      if (HasINFO) hash ^= INFO.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasRESULT) {
        output.WriteRawTag(8);
        output.WriteEnum((int) RESULT);
      }
      if (HasINFO) {
        output.WriteRawTag(18);
        output.WriteString(INFO);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasRESULT) {
        output.WriteRawTag(8);
        output.WriteEnum((int) RESULT);
      }
      if (HasINFO) {
        output.WriteRawTag(18);
        output.WriteString(INFO);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasRESULT) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RESULT);
      }
      if (HasINFO) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(INFO);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(STC_JOIN_ROOM other) {
      if (other == null) {
        return;
      }
      if (other.HasRESULT) {
        RESULT = other.RESULT;
      }
      if (other.HasINFO) {
        INFO = other.INFO;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RESULT = (global::MANGOROOMMSG.JOIN_RESULT) input.ReadEnum();
            break;
          }
          case 18: {
            INFO = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RESULT = (global::MANGOROOMMSG.JOIN_RESULT) input.ReadEnum();
            break;
          }
          case 18: {
            INFO = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class STC_PLAYER_CHANGE_NOTIFY : pb::IMessage<STC_PLAYER_CHANGE_NOTIFY>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<STC_PLAYER_CHANGE_NOTIFY> _parser = new pb::MessageParser<STC_PLAYER_CHANGE_NOTIFY>(() => new STC_PLAYER_CHANGE_NOTIFY());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<STC_PLAYER_CHANGE_NOTIFY> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MANGOROOMMSG.RoomMsgReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_PLAYER_CHANGE_NOTIFY() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_PLAYER_CHANGE_NOTIFY(STC_PLAYER_CHANGE_NOTIFY other) : this() {
      lISTPLAYERCHANGE_ = other.lISTPLAYERCHANGE_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_PLAYER_CHANGE_NOTIFY Clone() {
      return new STC_PLAYER_CHANGE_NOTIFY(this);
    }

    /// <summary>Field number for the "LIST_PLAYER_CHANGE" field.</summary>
    public const int LISTPLAYERCHANGEFieldNumber = 1;
    private static readonly pb::FieldCodec<global::MANGOROOMMSG.PLAYER_CHANGE> _repeated_lISTPLAYERCHANGE_codec
        = pb::FieldCodec.ForMessage(10, global::MANGOROOMMSG.PLAYER_CHANGE.Parser);
    private readonly pbc::RepeatedField<global::MANGOROOMMSG.PLAYER_CHANGE> lISTPLAYERCHANGE_ = new pbc::RepeatedField<global::MANGOROOMMSG.PLAYER_CHANGE>();
    /// <summary>
    /// 进入或离开玩家列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::MANGOROOMMSG.PLAYER_CHANGE> LISTPLAYERCHANGE {
      get { return lISTPLAYERCHANGE_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as STC_PLAYER_CHANGE_NOTIFY);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(STC_PLAYER_CHANGE_NOTIFY other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!lISTPLAYERCHANGE_.Equals(other.lISTPLAYERCHANGE_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= lISTPLAYERCHANGE_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      lISTPLAYERCHANGE_.WriteTo(output, _repeated_lISTPLAYERCHANGE_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      lISTPLAYERCHANGE_.WriteTo(ref output, _repeated_lISTPLAYERCHANGE_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += lISTPLAYERCHANGE_.CalculateSize(_repeated_lISTPLAYERCHANGE_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(STC_PLAYER_CHANGE_NOTIFY other) {
      if (other == null) {
        return;
      }
      lISTPLAYERCHANGE_.Add(other.lISTPLAYERCHANGE_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            lISTPLAYERCHANGE_.AddEntriesFrom(input, _repeated_lISTPLAYERCHANGE_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            lISTPLAYERCHANGE_.AddEntriesFrom(ref input, _repeated_lISTPLAYERCHANGE_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
