// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/msg_13_collocation.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace COLLOCATIONMSG {

  /// <summary>Holder for reflection information generated from protos/msg_13_collocation.proto</summary>
  public static partial class Msg13CollocationReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/msg_13_collocation.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Msg13CollocationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9wcm90b3MvbXNnXzEzX2NvbGxvY2F0aW9uLnByb3RvEg9DT0xMT0NBVElP",
            "Tl9NU0ciSQoNQ1RTX1RSSUFMX01TRxISCgpFVkVOVF9UWVBFGAEgAigNEhAK",
            "CEVWRU5UX0lEGAIgAigNEhIKCkVWRU5UX0RBVEEYAyABKAwiSQoNU1RDX1RS",
            "SUFMX01TRxISCgpFVkVOVF9UWVBFGAEgAigNEhAKCEVWRU5UX0lEGAIgAigN",
            "EhIKCkVWRU5UX0RBVEEYAyABKAwiNgoMQ1RTX1NZTkNfTVNHEhIKCkVWRU5U",
            "X1RZUEUYASACKA0SEgoKRVZFTlRfREFUQRgDIAEoDCI2CgxTVENfU1lOQ19N",
            "U0cSEgoKRVZFTlRfVFlQRRgBIAIoDRISCgpFVkVOVF9EQVRBGAMgASgMKiQK",
            "CENNRF9UWVBFEhgKFE1TR19UWVBFX0NPTExPQ0FUSU9OEA0qQgoGQ01EX0lE",
            "Eg0KCUNUU19UUklBTBABEg0KCVNUQ19UUklBTBACEgwKCENUU19TWU5DEAMS",
            "DAoIU1RDX1NZTkMQBEIsChdjbi5lZGVuLmdhdGV3YXkubWVzc2FnZUIPQ09M",
            "TE9DQVRJT05fTVNHSAM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::COLLOCATIONMSG.CMD_TYPE), typeof(global::COLLOCATIONMSG.CMD_ID), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::COLLOCATIONMSG.CTS_TRIAL_MSG), global::COLLOCATIONMSG.CTS_TRIAL_MSG.Parser, new[]{ "EVENTTYPE", "EVENTID", "EVENTDATA" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::COLLOCATIONMSG.STC_TRIAL_MSG), global::COLLOCATIONMSG.STC_TRIAL_MSG.Parser, new[]{ "EVENTTYPE", "EVENTID", "EVENTDATA" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::COLLOCATIONMSG.CTS_SYNC_MSG), global::COLLOCATIONMSG.CTS_SYNC_MSG.Parser, new[]{ "EVENTTYPE", "EVENTDATA" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::COLLOCATIONMSG.STC_SYNC_MSG), global::COLLOCATIONMSG.STC_SYNC_MSG.Parser, new[]{ "EVENTTYPE", "EVENTDATA" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum CMD_TYPE {
    [pbr::OriginalName("MSG_TYPE_COLLOCATION")] MsgTypeCollocation = 13,
  }

  public enum CMD_ID {
    [pbr::OriginalName("CTS_TRIAL")] CtsTrial = 1,
    [pbr::OriginalName("STC_TRIAL")] StcTrial = 2,
    [pbr::OriginalName("CTS_SYNC")] CtsSync = 3,
    [pbr::OriginalName("STC_SYNC")] StcSync = 4,
  }

  #endregion

  #region Messages
  public sealed partial class CTS_TRIAL_MSG : pb::IMessage<CTS_TRIAL_MSG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CTS_TRIAL_MSG> _parser = new pb::MessageParser<CTS_TRIAL_MSG>(() => new CTS_TRIAL_MSG());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CTS_TRIAL_MSG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::COLLOCATIONMSG.Msg13CollocationReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_TRIAL_MSG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_TRIAL_MSG(CTS_TRIAL_MSG other) : this() {
      _hasBits0 = other._hasBits0;
      eVENTTYPE_ = other.eVENTTYPE_;
      eVENTID_ = other.eVENTID_;
      eVENTDATA_ = other.eVENTDATA_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_TRIAL_MSG Clone() {
      return new CTS_TRIAL_MSG(this);
    }

    /// <summary>Field number for the "EVENT_TYPE" field.</summary>
    public const int EVENTTYPEFieldNumber = 1;
    private readonly static uint EVENTTYPEDefaultValue = 0;

    private uint eVENTTYPE_;
    /// <summary>
    ///抢占类事件类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EVENTTYPE {
      get { if ((_hasBits0 & 1) != 0) { return eVENTTYPE_; } else { return EVENTTYPEDefaultValue; } }
      set {
        _hasBits0 |= 1;
        eVENTTYPE_ = value;
      }
    }
    /// <summary>Gets whether the "EVENT_TYPE" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEVENTTYPE {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "EVENT_TYPE" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEVENTTYPE() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "EVENT_ID" field.</summary>
    public const int EVENTIDFieldNumber = 2;
    private readonly static uint EVENTIDDefaultValue = 0;

    private uint eVENTID_;
    /// <summary>
    ///事件ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EVENTID {
      get { if ((_hasBits0 & 2) != 0) { return eVENTID_; } else { return EVENTIDDefaultValue; } }
      set {
        _hasBits0 |= 2;
        eVENTID_ = value;
      }
    }
    /// <summary>Gets whether the "EVENT_ID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEVENTID {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "EVENT_ID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEVENTID() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "EVENT_DATA" field.</summary>
    public const int EVENTDATAFieldNumber = 3;
    private readonly static pb::ByteString EVENTDATADefaultValue = pb::ByteString.Empty;

    private pb::ByteString eVENTDATA_;
    /// <summary>
    ///事件数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString EVENTDATA {
      get { return eVENTDATA_ ?? EVENTDATADefaultValue; }
      set {
        eVENTDATA_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "EVENT_DATA" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEVENTDATA {
      get { return eVENTDATA_ != null; }
    }
    /// <summary>Clears the value of the "EVENT_DATA" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEVENTDATA() {
      eVENTDATA_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CTS_TRIAL_MSG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CTS_TRIAL_MSG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EVENTTYPE != other.EVENTTYPE) return false;
      if (EVENTID != other.EVENTID) return false;
      if (EVENTDATA != other.EVENTDATA) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasEVENTTYPE) hash ^= EVENTTYPE.GetHashCode();
      if (HasEVENTID) hash ^= EVENTID.GetHashCode();
      if (HasEVENTDATA) hash ^= EVENTDATA.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasEVENTTYPE) {
        output.WriteRawTag(8);
        output.WriteUInt32(EVENTTYPE);
      }
      if (HasEVENTID) {
        output.WriteRawTag(16);
        output.WriteUInt32(EVENTID);
      }
      if (HasEVENTDATA) {
        output.WriteRawTag(26);
        output.WriteBytes(EVENTDATA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasEVENTTYPE) {
        output.WriteRawTag(8);
        output.WriteUInt32(EVENTTYPE);
      }
      if (HasEVENTID) {
        output.WriteRawTag(16);
        output.WriteUInt32(EVENTID);
      }
      if (HasEVENTDATA) {
        output.WriteRawTag(26);
        output.WriteBytes(EVENTDATA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasEVENTTYPE) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EVENTTYPE);
      }
      if (HasEVENTID) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EVENTID);
      }
      if (HasEVENTDATA) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(EVENTDATA);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CTS_TRIAL_MSG other) {
      if (other == null) {
        return;
      }
      if (other.HasEVENTTYPE) {
        EVENTTYPE = other.EVENTTYPE;
      }
      if (other.HasEVENTID) {
        EVENTID = other.EVENTID;
      }
      if (other.HasEVENTDATA) {
        EVENTDATA = other.EVENTDATA;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EVENTTYPE = input.ReadUInt32();
            break;
          }
          case 16: {
            EVENTID = input.ReadUInt32();
            break;
          }
          case 26: {
            EVENTDATA = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EVENTTYPE = input.ReadUInt32();
            break;
          }
          case 16: {
            EVENTID = input.ReadUInt32();
            break;
          }
          case 26: {
            EVENTDATA = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class STC_TRIAL_MSG : pb::IMessage<STC_TRIAL_MSG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<STC_TRIAL_MSG> _parser = new pb::MessageParser<STC_TRIAL_MSG>(() => new STC_TRIAL_MSG());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<STC_TRIAL_MSG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::COLLOCATIONMSG.Msg13CollocationReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_TRIAL_MSG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_TRIAL_MSG(STC_TRIAL_MSG other) : this() {
      _hasBits0 = other._hasBits0;
      eVENTTYPE_ = other.eVENTTYPE_;
      eVENTID_ = other.eVENTID_;
      eVENTDATA_ = other.eVENTDATA_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_TRIAL_MSG Clone() {
      return new STC_TRIAL_MSG(this);
    }

    /// <summary>Field number for the "EVENT_TYPE" field.</summary>
    public const int EVENTTYPEFieldNumber = 1;
    private readonly static uint EVENTTYPEDefaultValue = 0;

    private uint eVENTTYPE_;
    /// <summary>
    ///事件类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EVENTTYPE {
      get { if ((_hasBits0 & 1) != 0) { return eVENTTYPE_; } else { return EVENTTYPEDefaultValue; } }
      set {
        _hasBits0 |= 1;
        eVENTTYPE_ = value;
      }
    }
    /// <summary>Gets whether the "EVENT_TYPE" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEVENTTYPE {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "EVENT_TYPE" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEVENTTYPE() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "EVENT_ID" field.</summary>
    public const int EVENTIDFieldNumber = 2;
    private readonly static uint EVENTIDDefaultValue = 0;

    private uint eVENTID_;
    /// <summary>
    ///事件ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EVENTID {
      get { if ((_hasBits0 & 2) != 0) { return eVENTID_; } else { return EVENTIDDefaultValue; } }
      set {
        _hasBits0 |= 2;
        eVENTID_ = value;
      }
    }
    /// <summary>Gets whether the "EVENT_ID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEVENTID {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "EVENT_ID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEVENTID() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "EVENT_DATA" field.</summary>
    public const int EVENTDATAFieldNumber = 3;
    private readonly static pb::ByteString EVENTDATADefaultValue = pb::ByteString.Empty;

    private pb::ByteString eVENTDATA_;
    /// <summary>
    ///事件数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString EVENTDATA {
      get { return eVENTDATA_ ?? EVENTDATADefaultValue; }
      set {
        eVENTDATA_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "EVENT_DATA" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEVENTDATA {
      get { return eVENTDATA_ != null; }
    }
    /// <summary>Clears the value of the "EVENT_DATA" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEVENTDATA() {
      eVENTDATA_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as STC_TRIAL_MSG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(STC_TRIAL_MSG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EVENTTYPE != other.EVENTTYPE) return false;
      if (EVENTID != other.EVENTID) return false;
      if (EVENTDATA != other.EVENTDATA) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasEVENTTYPE) hash ^= EVENTTYPE.GetHashCode();
      if (HasEVENTID) hash ^= EVENTID.GetHashCode();
      if (HasEVENTDATA) hash ^= EVENTDATA.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasEVENTTYPE) {
        output.WriteRawTag(8);
        output.WriteUInt32(EVENTTYPE);
      }
      if (HasEVENTID) {
        output.WriteRawTag(16);
        output.WriteUInt32(EVENTID);
      }
      if (HasEVENTDATA) {
        output.WriteRawTag(26);
        output.WriteBytes(EVENTDATA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasEVENTTYPE) {
        output.WriteRawTag(8);
        output.WriteUInt32(EVENTTYPE);
      }
      if (HasEVENTID) {
        output.WriteRawTag(16);
        output.WriteUInt32(EVENTID);
      }
      if (HasEVENTDATA) {
        output.WriteRawTag(26);
        output.WriteBytes(EVENTDATA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasEVENTTYPE) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EVENTTYPE);
      }
      if (HasEVENTID) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EVENTID);
      }
      if (HasEVENTDATA) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(EVENTDATA);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(STC_TRIAL_MSG other) {
      if (other == null) {
        return;
      }
      if (other.HasEVENTTYPE) {
        EVENTTYPE = other.EVENTTYPE;
      }
      if (other.HasEVENTID) {
        EVENTID = other.EVENTID;
      }
      if (other.HasEVENTDATA) {
        EVENTDATA = other.EVENTDATA;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EVENTTYPE = input.ReadUInt32();
            break;
          }
          case 16: {
            EVENTID = input.ReadUInt32();
            break;
          }
          case 26: {
            EVENTDATA = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EVENTTYPE = input.ReadUInt32();
            break;
          }
          case 16: {
            EVENTID = input.ReadUInt32();
            break;
          }
          case 26: {
            EVENTDATA = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CTS_SYNC_MSG : pb::IMessage<CTS_SYNC_MSG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CTS_SYNC_MSG> _parser = new pb::MessageParser<CTS_SYNC_MSG>(() => new CTS_SYNC_MSG());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CTS_SYNC_MSG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::COLLOCATIONMSG.Msg13CollocationReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_SYNC_MSG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_SYNC_MSG(CTS_SYNC_MSG other) : this() {
      _hasBits0 = other._hasBits0;
      eVENTTYPE_ = other.eVENTTYPE_;
      eVENTDATA_ = other.eVENTDATA_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_SYNC_MSG Clone() {
      return new CTS_SYNC_MSG(this);
    }

    /// <summary>Field number for the "EVENT_TYPE" field.</summary>
    public const int EVENTTYPEFieldNumber = 1;
    private readonly static uint EVENTTYPEDefaultValue = 0;

    private uint eVENTTYPE_;
    /// <summary>
    ///同步类事件类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EVENTTYPE {
      get { if ((_hasBits0 & 1) != 0) { return eVENTTYPE_; } else { return EVENTTYPEDefaultValue; } }
      set {
        _hasBits0 |= 1;
        eVENTTYPE_ = value;
      }
    }
    /// <summary>Gets whether the "EVENT_TYPE" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEVENTTYPE {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "EVENT_TYPE" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEVENTTYPE() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "EVENT_DATA" field.</summary>
    public const int EVENTDATAFieldNumber = 3;
    private readonly static pb::ByteString EVENTDATADefaultValue = pb::ByteString.Empty;

    private pb::ByteString eVENTDATA_;
    /// <summary>
    ///事件数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString EVENTDATA {
      get { return eVENTDATA_ ?? EVENTDATADefaultValue; }
      set {
        eVENTDATA_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "EVENT_DATA" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEVENTDATA {
      get { return eVENTDATA_ != null; }
    }
    /// <summary>Clears the value of the "EVENT_DATA" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEVENTDATA() {
      eVENTDATA_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CTS_SYNC_MSG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CTS_SYNC_MSG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EVENTTYPE != other.EVENTTYPE) return false;
      if (EVENTDATA != other.EVENTDATA) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasEVENTTYPE) hash ^= EVENTTYPE.GetHashCode();
      if (HasEVENTDATA) hash ^= EVENTDATA.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasEVENTTYPE) {
        output.WriteRawTag(8);
        output.WriteUInt32(EVENTTYPE);
      }
      if (HasEVENTDATA) {
        output.WriteRawTag(26);
        output.WriteBytes(EVENTDATA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasEVENTTYPE) {
        output.WriteRawTag(8);
        output.WriteUInt32(EVENTTYPE);
      }
      if (HasEVENTDATA) {
        output.WriteRawTag(26);
        output.WriteBytes(EVENTDATA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasEVENTTYPE) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EVENTTYPE);
      }
      if (HasEVENTDATA) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(EVENTDATA);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CTS_SYNC_MSG other) {
      if (other == null) {
        return;
      }
      if (other.HasEVENTTYPE) {
        EVENTTYPE = other.EVENTTYPE;
      }
      if (other.HasEVENTDATA) {
        EVENTDATA = other.EVENTDATA;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EVENTTYPE = input.ReadUInt32();
            break;
          }
          case 26: {
            EVENTDATA = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EVENTTYPE = input.ReadUInt32();
            break;
          }
          case 26: {
            EVENTDATA = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class STC_SYNC_MSG : pb::IMessage<STC_SYNC_MSG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<STC_SYNC_MSG> _parser = new pb::MessageParser<STC_SYNC_MSG>(() => new STC_SYNC_MSG());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<STC_SYNC_MSG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::COLLOCATIONMSG.Msg13CollocationReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_SYNC_MSG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_SYNC_MSG(STC_SYNC_MSG other) : this() {
      _hasBits0 = other._hasBits0;
      eVENTTYPE_ = other.eVENTTYPE_;
      eVENTDATA_ = other.eVENTDATA_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_SYNC_MSG Clone() {
      return new STC_SYNC_MSG(this);
    }

    /// <summary>Field number for the "EVENT_TYPE" field.</summary>
    public const int EVENTTYPEFieldNumber = 1;
    private readonly static uint EVENTTYPEDefaultValue = 0;

    private uint eVENTTYPE_;
    /// <summary>
    ///同步类事件类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EVENTTYPE {
      get { if ((_hasBits0 & 1) != 0) { return eVENTTYPE_; } else { return EVENTTYPEDefaultValue; } }
      set {
        _hasBits0 |= 1;
        eVENTTYPE_ = value;
      }
    }
    /// <summary>Gets whether the "EVENT_TYPE" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEVENTTYPE {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "EVENT_TYPE" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEVENTTYPE() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "EVENT_DATA" field.</summary>
    public const int EVENTDATAFieldNumber = 3;
    private readonly static pb::ByteString EVENTDATADefaultValue = pb::ByteString.Empty;

    private pb::ByteString eVENTDATA_;
    /// <summary>
    ///事件数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString EVENTDATA {
      get { return eVENTDATA_ ?? EVENTDATADefaultValue; }
      set {
        eVENTDATA_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "EVENT_DATA" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEVENTDATA {
      get { return eVENTDATA_ != null; }
    }
    /// <summary>Clears the value of the "EVENT_DATA" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEVENTDATA() {
      eVENTDATA_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as STC_SYNC_MSG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(STC_SYNC_MSG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EVENTTYPE != other.EVENTTYPE) return false;
      if (EVENTDATA != other.EVENTDATA) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasEVENTTYPE) hash ^= EVENTTYPE.GetHashCode();
      if (HasEVENTDATA) hash ^= EVENTDATA.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasEVENTTYPE) {
        output.WriteRawTag(8);
        output.WriteUInt32(EVENTTYPE);
      }
      if (HasEVENTDATA) {
        output.WriteRawTag(26);
        output.WriteBytes(EVENTDATA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasEVENTTYPE) {
        output.WriteRawTag(8);
        output.WriteUInt32(EVENTTYPE);
      }
      if (HasEVENTDATA) {
        output.WriteRawTag(26);
        output.WriteBytes(EVENTDATA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasEVENTTYPE) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EVENTTYPE);
      }
      if (HasEVENTDATA) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(EVENTDATA);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(STC_SYNC_MSG other) {
      if (other == null) {
        return;
      }
      if (other.HasEVENTTYPE) {
        EVENTTYPE = other.EVENTTYPE;
      }
      if (other.HasEVENTDATA) {
        EVENTDATA = other.EVENTDATA;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EVENTTYPE = input.ReadUInt32();
            break;
          }
          case 26: {
            EVENTDATA = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EVENTTYPE = input.ReadUInt32();
            break;
          }
          case 26: {
            EVENTDATA = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
