// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/msg_5_activity.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ACTIVITYMSG {

  /// <summary>Holder for reflection information generated from protos/msg_5_activity.proto</summary>
  public static partial class Msg5ActivityReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/msg_5_activity.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Msg5ActivityReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chtwcm90b3MvbXNnXzVfYWN0aXZpdHkucHJvdG8SDEFDVElWSVRZX01TRyI/",
            "ChRTVENfU1RSRUVUX0RBTkNFX01TRxITCgtEQU5DRV9JTkRFWBgBIAIoDRIS",
            "CgpEQU5DRV9USU1FGAIgAigNIiQKEkNUU19TVFJFRVRfQ01EX01TRxIOCgZD",
            "TURfSUQYASACKAkiXwoSU1RDX1NUUkVFVF9DTURfTVNHEg4KBkNNRF9JRBgB",
            "IAIoCRIrCgZSRVNVTFQYAiACKA4yGy5BQ1RJVklUWV9NU0cuQUNUSU9OX1JF",
            "U1VMVBIMCgRJTkZPGAMgASgJKiEKCENNRF9UWVBFEhUKEU1TR19UWVBFX0FD",
            "VElWSVRZEAUqKAoNQUNUSU9OX1JFU1VMVBILCgdTVUNDRVNTEAESCgoGRkFJ",
            "TEVEEAIqXAoGQ01EX0lEEhQKEFNUQ19TVFJFRVRfREFOQ0UQARIUChBDVFNf",
            "U1RSRUVUX0RBTkNFEAISEgoOQ1RTX1NUUkVFVF9DTUQQAxISCg5TVENfU1RS",
            "RUVUX0NNRBAEQikKF2NuLmVkZW4uZ2F0ZXdheS5tZXNzYWdlQgxBQ1RJVklU",
            "WV9NU0dIAw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ACTIVITYMSG.CMD_TYPE), typeof(global::ACTIVITYMSG.ACTION_RESULT), typeof(global::ACTIVITYMSG.CMD_ID), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ACTIVITYMSG.STC_STREET_DANCE_MSG), global::ACTIVITYMSG.STC_STREET_DANCE_MSG.Parser, new[]{ "DANCEINDEX", "DANCETIME" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ACTIVITYMSG.CTS_STREET_CMD_MSG), global::ACTIVITYMSG.CTS_STREET_CMD_MSG.Parser, new[]{ "CMDID" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ACTIVITYMSG.STC_STREET_CMD_MSG), global::ACTIVITYMSG.STC_STREET_CMD_MSG.Parser, new[]{ "CMDID", "RESULT", "INFO" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum CMD_TYPE {
    [pbr::OriginalName("MSG_TYPE_ACTIVITY")] MsgTypeActivity = 5,
  }

  public enum ACTION_RESULT {
    [pbr::OriginalName("SUCCESS")] Success = 1,
    [pbr::OriginalName("FAILED")] Failed = 2,
  }

  public enum CMD_ID {
    [pbr::OriginalName("STC_STREET_DANCE")] StcStreetDance = 1,
    [pbr::OriginalName("CTS_STREET_DANCE")] CtsStreetDance = 2,
    [pbr::OriginalName("CTS_STREET_CMD")] CtsStreetCmd = 3,
    [pbr::OriginalName("STC_STREET_CMD")] StcStreetCmd = 4,
  }

  #endregion

  #region Messages
  public sealed partial class STC_STREET_DANCE_MSG : pb::IMessage<STC_STREET_DANCE_MSG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<STC_STREET_DANCE_MSG> _parser = new pb::MessageParser<STC_STREET_DANCE_MSG>(() => new STC_STREET_DANCE_MSG());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<STC_STREET_DANCE_MSG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ACTIVITYMSG.Msg5ActivityReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_STREET_DANCE_MSG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_STREET_DANCE_MSG(STC_STREET_DANCE_MSG other) : this() {
      _hasBits0 = other._hasBits0;
      dANCEINDEX_ = other.dANCEINDEX_;
      dANCETIME_ = other.dANCETIME_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_STREET_DANCE_MSG Clone() {
      return new STC_STREET_DANCE_MSG(this);
    }

    /// <summary>Field number for the "DANCE_INDEX" field.</summary>
    public const int DANCEINDEXFieldNumber = 1;
    private readonly static uint DANCEINDEXDefaultValue = 0;

    private uint dANCEINDEX_;
    /// <summary>
    /// 舞蹈编号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DANCEINDEX {
      get { if ((_hasBits0 & 1) != 0) { return dANCEINDEX_; } else { return DANCEINDEXDefaultValue; } }
      set {
        _hasBits0 |= 1;
        dANCEINDEX_ = value;
      }
    }
    /// <summary>Gets whether the "DANCE_INDEX" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDANCEINDEX {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "DANCE_INDEX" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDANCEINDEX() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "DANCE_TIME" field.</summary>
    public const int DANCETIMEFieldNumber = 2;
    private readonly static uint DANCETIMEDefaultValue = 0;

    private uint dANCETIME_;
    /// <summary>
    ///舞蹈已持续时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DANCETIME {
      get { if ((_hasBits0 & 2) != 0) { return dANCETIME_; } else { return DANCETIMEDefaultValue; } }
      set {
        _hasBits0 |= 2;
        dANCETIME_ = value;
      }
    }
    /// <summary>Gets whether the "DANCE_TIME" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDANCETIME {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "DANCE_TIME" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDANCETIME() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as STC_STREET_DANCE_MSG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(STC_STREET_DANCE_MSG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DANCEINDEX != other.DANCEINDEX) return false;
      if (DANCETIME != other.DANCETIME) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasDANCEINDEX) hash ^= DANCEINDEX.GetHashCode();
      if (HasDANCETIME) hash ^= DANCETIME.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasDANCEINDEX) {
        output.WriteRawTag(8);
        output.WriteUInt32(DANCEINDEX);
      }
      if (HasDANCETIME) {
        output.WriteRawTag(16);
        output.WriteUInt32(DANCETIME);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasDANCEINDEX) {
        output.WriteRawTag(8);
        output.WriteUInt32(DANCEINDEX);
      }
      if (HasDANCETIME) {
        output.WriteRawTag(16);
        output.WriteUInt32(DANCETIME);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasDANCEINDEX) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DANCEINDEX);
      }
      if (HasDANCETIME) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DANCETIME);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(STC_STREET_DANCE_MSG other) {
      if (other == null) {
        return;
      }
      if (other.HasDANCEINDEX) {
        DANCEINDEX = other.DANCEINDEX;
      }
      if (other.HasDANCETIME) {
        DANCETIME = other.DANCETIME;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DANCEINDEX = input.ReadUInt32();
            break;
          }
          case 16: {
            DANCETIME = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DANCEINDEX = input.ReadUInt32();
            break;
          }
          case 16: {
            DANCETIME = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CTS_STREET_CMD_MSG : pb::IMessage<CTS_STREET_CMD_MSG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CTS_STREET_CMD_MSG> _parser = new pb::MessageParser<CTS_STREET_CMD_MSG>(() => new CTS_STREET_CMD_MSG());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CTS_STREET_CMD_MSG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ACTIVITYMSG.Msg5ActivityReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_STREET_CMD_MSG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_STREET_CMD_MSG(CTS_STREET_CMD_MSG other) : this() {
      cMDID_ = other.cMDID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CTS_STREET_CMD_MSG Clone() {
      return new CTS_STREET_CMD_MSG(this);
    }

    /// <summary>Field number for the "CMD_ID" field.</summary>
    public const int CMDIDFieldNumber = 1;
    private readonly static string CMDIDDefaultValue = "";

    private string cMDID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CMDID {
      get { return cMDID_ ?? CMDIDDefaultValue; }
      set {
        cMDID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "CMD_ID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCMDID {
      get { return cMDID_ != null; }
    }
    /// <summary>Clears the value of the "CMD_ID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCMDID() {
      cMDID_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CTS_STREET_CMD_MSG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CTS_STREET_CMD_MSG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CMDID != other.CMDID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasCMDID) hash ^= CMDID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasCMDID) {
        output.WriteRawTag(10);
        output.WriteString(CMDID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasCMDID) {
        output.WriteRawTag(10);
        output.WriteString(CMDID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasCMDID) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CMDID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CTS_STREET_CMD_MSG other) {
      if (other == null) {
        return;
      }
      if (other.HasCMDID) {
        CMDID = other.CMDID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CMDID = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CMDID = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class STC_STREET_CMD_MSG : pb::IMessage<STC_STREET_CMD_MSG>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<STC_STREET_CMD_MSG> _parser = new pb::MessageParser<STC_STREET_CMD_MSG>(() => new STC_STREET_CMD_MSG());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<STC_STREET_CMD_MSG> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ACTIVITYMSG.Msg5ActivityReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_STREET_CMD_MSG() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_STREET_CMD_MSG(STC_STREET_CMD_MSG other) : this() {
      _hasBits0 = other._hasBits0;
      cMDID_ = other.cMDID_;
      rESULT_ = other.rESULT_;
      iNFO_ = other.iNFO_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public STC_STREET_CMD_MSG Clone() {
      return new STC_STREET_CMD_MSG(this);
    }

    /// <summary>Field number for the "CMD_ID" field.</summary>
    public const int CMDIDFieldNumber = 1;
    private readonly static string CMDIDDefaultValue = "";

    private string cMDID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CMDID {
      get { return cMDID_ ?? CMDIDDefaultValue; }
      set {
        cMDID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "CMD_ID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCMDID {
      get { return cMDID_ != null; }
    }
    /// <summary>Clears the value of the "CMD_ID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCMDID() {
      cMDID_ = null;
    }

    /// <summary>Field number for the "RESULT" field.</summary>
    public const int RESULTFieldNumber = 2;
    private readonly static global::ACTIVITYMSG.ACTION_RESULT RESULTDefaultValue = global::ACTIVITYMSG.ACTION_RESULT.Success;

    private global::ACTIVITYMSG.ACTION_RESULT rESULT_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ACTIVITYMSG.ACTION_RESULT RESULT {
      get { if ((_hasBits0 & 1) != 0) { return rESULT_; } else { return RESULTDefaultValue; } }
      set {
        _hasBits0 |= 1;
        rESULT_ = value;
      }
    }
    /// <summary>Gets whether the "RESULT" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRESULT {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "RESULT" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRESULT() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "INFO" field.</summary>
    public const int INFOFieldNumber = 3;
    private readonly static string INFODefaultValue = "";

    private string iNFO_;
    /// <summary>
    ///结果信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string INFO {
      get { return iNFO_ ?? INFODefaultValue; }
      set {
        iNFO_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "INFO" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasINFO {
      get { return iNFO_ != null; }
    }
    /// <summary>Clears the value of the "INFO" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearINFO() {
      iNFO_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as STC_STREET_CMD_MSG);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(STC_STREET_CMD_MSG other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CMDID != other.CMDID) return false;
      if (RESULT != other.RESULT) return false;
      if (INFO != other.INFO) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasCMDID) hash ^= CMDID.GetHashCode();
      if (HasRESULT) hash ^= RESULT.GetHashCode();
      if (HasINFO) hash ^= INFO.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasCMDID) {
        output.WriteRawTag(10);
        output.WriteString(CMDID);
      }
      if (HasRESULT) {
        output.WriteRawTag(16);
        output.WriteEnum((int) RESULT);
      }
      if (HasINFO) {
        output.WriteRawTag(26);
        output.WriteString(INFO);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasCMDID) {
        output.WriteRawTag(10);
        output.WriteString(CMDID);
      }
      if (HasRESULT) {
        output.WriteRawTag(16);
        output.WriteEnum((int) RESULT);
      }
      if (HasINFO) {
        output.WriteRawTag(26);
        output.WriteString(INFO);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasCMDID) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CMDID);
      }
      if (HasRESULT) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RESULT);
      }
      if (HasINFO) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(INFO);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(STC_STREET_CMD_MSG other) {
      if (other == null) {
        return;
      }
      if (other.HasCMDID) {
        CMDID = other.CMDID;
      }
      if (other.HasRESULT) {
        RESULT = other.RESULT;
      }
      if (other.HasINFO) {
        INFO = other.INFO;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CMDID = input.ReadString();
            break;
          }
          case 16: {
            RESULT = (global::ACTIVITYMSG.ACTION_RESULT) input.ReadEnum();
            break;
          }
          case 26: {
            INFO = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CMDID = input.ReadString();
            break;
          }
          case 16: {
            RESULT = (global::ACTIVITYMSG.ACTION_RESULT) input.ReadEnum();
            break;
          }
          case 26: {
            INFO = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
